# Preface {#Preface .unnumbered}

**Caution! - Work in progress.**

This handbook is geared towards young water professionals in Central Asia. It consists of two main parts. Part I presents the hydrological systems of the region. This part fuses a selective synthesis Victor Shults' famous Russian book "Rivers of Middle Asia", published as second edition in 1965 with modern insights and knowledge from recent research [@shults_RiversOfMiddleAsia]. I hope that this combination provides an attractive, approachable and yet scientifically sound introduction to the many interesting hydrological features of this diverse region. The Chirchik River Basin will be highlighted in a separate Chapter and discussed at length since it serves as demonstration for the different modeling approaches introduced and discussed in Part II.

Part II provides a learning manual to equip students with a hands-on guide on how to conceptualize, implement, calibrate, run and validate hydrological models. First, predictive inference is presented. This is an approach that is used in the Central Asian Hydromets to predict river discharge at various lead times, from days up to months and seasons. At the core of this approach is to use past observations of hydro-metorological variables to predict future discharge with different types of statistical models. Second, hydrologic-hydraulic modeling is presented. This type of modeling is most often used for river basin planning and for climate impact assessments. The philosophy of working by example is followed and all concepts and modeling approaches are discussed in the context of the sample catchment of the Chirchik River whose tributaries are shared by Uzbekistan and Kyrgyzstan. 

The book's emphasis is on the strict use of open-source software.

The author is grateful for the support by the Global Water Programme at the Swiss Agency for Development and Cooperation and especially to Stephanie Piers de Raveschroot and Andre Wehrli there. The author owes a lot to Andrey Yakovlev who provided invaluable guidance throughout his professional career. 

Finally, this book is dedicated to our past, current and future collegues at the Central Asian Hydrometeorological Agencies whose tireless work in collecting and analysing hydro-meteorological data in Central Asia has helped to greatly improve our understanding of the complex runoff generation processes at work there. 

::: {style="text-align: right"}
Tobias Siegfried
:::

::: {style="text-align: right"}
Zurich, December 2020
:::
