<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Case Study | Applied Modeling of Hydrological Systems in Central Asia</title>
  <meta name="description" content="This is a course book on Central Asia hydrological systems and hydrological modeling." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Case Study | Applied Modeling of Hydrological Systems in Central Asia" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a course book on Central Asia hydrological systems and hydrological modeling." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Case Study | Applied Modeling of Hydrological Systems in Central Asia" />
  
  <meta name="twitter:description" content="This is a course book on Central Asia hydrological systems and hydrological modeling." />
  

<meta name="author" content="Tobias Siegfried" />


<meta name="date" content="2020-11-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="05_Irrigation_CentralAsia.html"/>
<link rel="next" href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Hydrological Systems in Central Asia</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="01_Preface.html"><a href="01_Preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="02_Foreword.html"><a href="02_Foreword.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="part"><span><b>I Part I Hydrological Systems</b></span></li>
<li class="chapter" data-level="1" data-path="03_PI_Introduction.html"><a href="03_PI_Introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="04_Hydrological_Systems.html"><a href="04_Hydrological_Systems.html"><i class="fa fa-check"></i><b>2</b> Hydrological Systems in Central Asia</a>
<ul>
<li class="chapter" data-level="2.1" data-path="04_Hydrological_Systems.html"><a href="04_Hydrological_Systems.html#regional-hydro-climatological-features"><i class="fa fa-check"></i><b>2.1</b> Regional Hydro-Climatological Features</a></li>
<li class="chapter" data-level="2.2" data-path="04_Hydrological_Systems.html"><a href="04_Hydrological_Systems.html#chap:regionalWaterBalance"><i class="fa fa-check"></i><b>2.2</b> Regional Water Balance</a></li>
<li class="chapter" data-level="2.3" data-path="04_Hydrological_Systems.html"><a href="04_Hydrological_Systems.html#runoff-formation"><i class="fa fa-check"></i><b>2.3</b> Runoff Formation</a></li>
<li class="chapter" data-level="2.4" data-path="04_Hydrological_Systems.html"><a href="04_Hydrological_Systems.html#average-multi-year-runoff"><i class="fa fa-check"></i><b>2.4</b> Average Multi-Year Runoff</a></li>
<li class="chapter" data-level="2.5" data-path="04_Hydrological_Systems.html"><a href="04_Hydrological_Systems.html#annual-runoff-fluctuations"><i class="fa fa-check"></i><b>2.5</b> Annual Runoff Fluctuations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="05_Irrigation_CentralAsia.html"><a href="05_Irrigation_CentralAsia.html"><i class="fa fa-check"></i><b>3</b> Irrigation Agriculture in Central Asia</a>
<ul>
<li class="chapter" data-level="3.1" data-path="05_Irrigation_CentralAsia.html"><a href="05_Irrigation_CentralAsia.html#historic-developments"><i class="fa fa-check"></i><b>3.1</b> Historic Developments</a></li>
<li class="chapter" data-level="3.2" data-path="05_Irrigation_CentralAsia.html"><a href="05_Irrigation_CentralAsia.html#irrigation-and-socio-economic-activity-in-the-twentieth-century"><i class="fa fa-check"></i><b>3.2</b> Irrigation and Socio-Economic Activity in the Twentieth Century</a></li>
<li class="chapter" data-level="3.3" data-path="05_Irrigation_CentralAsia.html"><a href="05_Irrigation_CentralAsia.html#post-transition-developments-in-the-irrigation-sectors"><i class="fa fa-check"></i><b>3.3</b> Post-Transition Developments in the Irrigation Sectors</a></li>
</ul></li>
<li class="part"><span><b>II Part II Applied Modeling</b></span></li>
<li class="chapter" data-level="4" data-path="06_CaseStudy_ChirchikRiver.html"><a href="06_CaseStudy_ChirchikRiver.html"><i class="fa fa-check"></i><b>4</b> Case Study</a>
<ul>
<li class="chapter" data-level="" data-path="06_CaseStudy_ChirchikRiver.html"><a href="06_CaseStudy_ChirchikRiver.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="4.1" data-path="06_CaseStudy_ChirchikRiver.html"><a href="06_CaseStudy_ChirchikRiver.html#CaseStudyChirchikRiver"><i class="fa fa-check"></i><b>4.1</b> The Chirchik River Basin</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="06_CaseStudy_ChirchikRiver.html"><a href="06_CaseStudy_ChirchikRiver.html#overview"><i class="fa fa-check"></i><b>4.1.1</b> Overview</a></li>
<li class="chapter" data-level="4.1.2" data-path="06_CaseStudy_ChirchikRiver.html"><a href="06_CaseStudy_ChirchikRiver.html#discharge-estimation-in-ungauged-subcatchments"><i class="fa fa-check"></i><b>4.1.2</b> Discharge Estimation in Ungauged Subcatchments</a></li>
<li class="chapter" data-level="4.1.3" data-path="06_CaseStudy_ChirchikRiver.html"><a href="06_CaseStudy_ChirchikRiver.html#analysis-of-available-data"><i class="fa fa-check"></i><b>4.1.3</b> Analysis of Available Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><i class="fa fa-check"></i><b>5</b> Retrieval &amp; Analysis of Data</a>
<ul>
<li class="chapter" data-level="" data-path="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html#preliminary-remarks"><i class="fa fa-check"></i>Preliminary Remarks</a></li>
<li class="chapter" data-level="5.1" data-path="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html#GeospatialData"><i class="fa fa-check"></i><b>5.1</b> Geospatial Data</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html#CatchmentDelineation"><i class="fa fa-check"></i><b>5.1.1</b> Catchment Delineation</a></li>
<li class="chapter" data-level="5.1.2" data-path="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html#computation-of-elevation-bands"><i class="fa fa-check"></i><b>5.1.2</b> Computation of Elevation Bands</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html#climate-data"><i class="fa fa-check"></i><b>5.2</b> Climate Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html#access-select-and-download-era5-reanalysis-data"><i class="fa fa-check"></i><b>5.2.1</b> Access, Select and Download ERA5 Reanalysis Data</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html"><a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html#hydrological-data"><i class="fa fa-check"></i><b>5.3</b> Hydrological Data</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html"><i class="fa fa-check"></i><b>6</b> The Manual Water Balance</a>
<ul>
<li class="chapter" data-level="6.1" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#site-problem-description"><i class="fa fa-check"></i><b>6.1</b> Site &amp; problem description</a></li>
<li class="chapter" data-level="6.2" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#identification-of-the-dominant-flow-processes"><i class="fa fa-check"></i><b>6.2</b> Identification of the dominant flow processes</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#precipitation"><i class="fa fa-check"></i><b>6.2.1</b> Precipitation</a></li>
<li class="chapter" data-level="6.2.2" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#evaporation"><i class="fa fa-check"></i><b>6.2.2</b> Evaporation</a></li>
<li class="chapter" data-level="6.2.3" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#transpiration"><i class="fa fa-check"></i><b>6.2.3</b> Transpiration</a></li>
<li class="chapter" data-level="6.2.4" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#canopy-interception"><i class="fa fa-check"></i><b>6.2.4</b> Canopy interception</a></li>
<li class="chapter" data-level="6.2.5" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#snowmelt"><i class="fa fa-check"></i><b>6.2.5</b> Snowmelt</a></li>
<li class="chapter" data-level="6.2.6" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#runoff"><i class="fa fa-check"></i><b>6.2.6</b> Runoff</a></li>
<li class="chapter" data-level="6.2.7" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#infiltration"><i class="fa fa-check"></i><b>6.2.7</b> Infiltration</a></li>
<li class="chapter" data-level="6.2.8" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#sub-surface-flow"><i class="fa fa-check"></i><b>6.2.8</b> Sub-surface flow</a></li>
<li class="chapter" data-level="6.2.9" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#sublimation"><i class="fa fa-check"></i><b>6.2.9</b> Sublimation</a></li>
<li class="chapter" data-level="6.2.10" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#percolation"><i class="fa fa-check"></i><b>6.2.10</b> Percolation</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#the-general-water-balance-equation"><i class="fa fa-check"></i><b>6.3</b> The general water balance equation</a></li>
<li class="chapter" data-level="6.4" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#boundaries-of-the-water-balance"><i class="fa fa-check"></i><b>6.4</b> Boundaries of the water balance</a></li>
<li class="chapter" data-level="6.5" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#data-need-for-a-water-balance"><i class="fa fa-check"></i><b>6.5</b> Data need for a water balance</a></li>
<li class="chapter" data-level="6.6" data-path="08_FirstSteps-ManualWaterBalance.html"><a href="08_FirstSteps-ManualWaterBalance.html#setting-up-a-conceptual-model"><i class="fa fa-check"></i><b>6.6</b> Setting up a conceptual model</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="09_PhysicallyBased_Models.html"><a href="09_PhysicallyBased_Models.html"><i class="fa fa-check"></i><b>7</b> Hydrological Modeling: Physically-Based Models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="09_PhysicallyBased_Models.html"><a href="09_PhysicallyBased_Models.html#background-on-physically-based-modeling"><i class="fa fa-check"></i><b>7.1</b> Background on Physically-Based Modeling</a></li>
<li class="chapter" data-level="7.2" data-path="09_PhysicallyBased_Models.html"><a href="09_PhysicallyBased_Models.html#model-setup"><i class="fa fa-check"></i><b>7.2</b> Model Setup</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="09_PhysicallyBased_Models.html"><a href="09_PhysicallyBased_Models.html#zone-of-runoff-formation"><i class="fa fa-check"></i><b>7.2.1</b> Zone of Runoff Formation</a></li>
<li class="chapter" data-level="7.2.2" data-path="09_PhysicallyBased_Models.html"><a href="09_PhysicallyBased_Models.html#zone-of-water-distribution-and-consumption"><i class="fa fa-check"></i><b>7.2.2</b> Zone of Water Distribution and Consumption</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="09_PhysicallyBased_Models.html"><a href="09_PhysicallyBased_Models.html#model-calibration-and-validation"><i class="fa fa-check"></i><b>7.3</b> Model Calibration and Validation</a></li>
<li class="chapter" data-level="7.4" data-path="09_PhysicallyBased_Models.html"><a href="09_PhysicallyBased_Models.html#discussion"><i class="fa fa-check"></i><b>7.4</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html"><i class="fa fa-check"></i><b>8</b> Hydrological Modeling: Empirical Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html#background-on-empirical-modeling"><i class="fa fa-check"></i><b>8.1</b> Background on Empirical Modeling</a></li>
<li class="chapter" data-level="8.2" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html#key-forecasting-techniques"><i class="fa fa-check"></i><b>8.2</b> Key Forecasting Techniques</a></li>
<li class="chapter" data-level="8.3" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html#getting-started"><i class="fa fa-check"></i><b>8.3</b> Getting Started</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html#loading-the-required-packages-and-data"><i class="fa fa-check"></i><b>8.3.1</b> Loading the Required Packages and Data</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html#exploratory-data-analysis-data-preparation"><i class="fa fa-check"></i><b>8.4</b> Exploratory Data Analysis &amp; Data Preparation</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html#discharge-data"><i class="fa fa-check"></i><b>8.4.1</b> Discharge Data</a></li>
<li class="chapter" data-level="8.4.2" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html#meteorological-data"><i class="fa fa-check"></i><b>8.4.2</b> Meteorological Data</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="10_EmpiricalModels.html"><a href="10_EmpiricalModels.html#gap-filling"><i class="fa fa-check"></i><b>8.5</b> Gap Filling</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="11_Operationalization.html"><a href="11_Operationalization.html"><i class="fa fa-check"></i><b>9</b> Operationalization of Models - Opportunities and Challenges</a>
<ul>
<li class="chapter" data-level="9.1" data-path="11_Operationalization.html"><a href="11_Operationalization.html#co-design-phase"><i class="fa fa-check"></i><b>9.1</b> Co-design Phase</a></li>
<li class="chapter" data-level="9.2" data-path="11_Operationalization.html"><a href="11_Operationalization.html#modeling-phase"><i class="fa fa-check"></i><b>9.2</b> Modeling Phase</a></li>
<li class="chapter" data-level="9.3" data-path="11_Operationalization.html"><a href="11_Operationalization.html#testing-phase"><i class="fa fa-check"></i><b>9.3</b> Testing Phase</a></li>
<li class="chapter" data-level="9.4" data-path="11_Operationalization.html"><a href="11_Operationalization.html#operational-deployment"><i class="fa fa-check"></i><b>9.4</b> Operational Deployment</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="12_Appendix_Software.html"><a href="12_Appendix_Software.html"><i class="fa fa-check"></i><b>10</b> (APPENDIX) Appendix</a></li>
<li class="chapter" data-level="11" data-path="12_Appendix_Software.html"><a href="12_Appendix_Software.html#appendix-a"><i class="fa fa-check"></i><b>11</b> Appendix A</a>
<ul>
<li class="chapter" data-level="11.1" data-path="12_Appendix_Software.html"><a href="12_Appendix_Software.html#open-source-software"><i class="fa fa-check"></i><b>11.1</b> Open-Source Software</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="12_Appendix_Software.html"><a href="12_Appendix_Software.html#qgis"><i class="fa fa-check"></i><b>11.1.1</b> QGIS</a></li>
<li class="chapter" data-level="11.1.2" data-path="12_Appendix_Software.html"><a href="12_Appendix_Software.html#r-and-rstudio"><i class="fa fa-check"></i><b>11.1.2</b> R and RStudio</a></li>
<li class="chapter" data-level="11.1.3" data-path="12_Appendix_Software.html"><a href="12_Appendix_Software.html#rs-minerve"><i class="fa fa-check"></i><b>11.1.3</b> RS Minerve</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="13_references.html"><a href="13_references.html"><i class="fa fa-check"></i><b>12</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Modeling of Hydrological Systems in Central Asia</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="Case_Study" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Case Study</h1>
<div id="prerequisites" class="section level2 unnumbered">
<h2>Prerequisites</h2>
<p>This is the first ‘practical’ Chapter of the book and comes with software requirements. For the analysis of the available data we use R <span class="citation">(<a href="13_references.html#ref-R-2013" role="doc-biblioref">R Core Team 2013</a>)</span>. R is a computer language and environment for data analysis, statistical computation and data visualization. It can be downloaded at &lt;<a href="https://www.r-project.org" class="uri">https://www.r-project.org</a>&gt;. Together with R, we are using RStudio as the IDE <span class="citation">(<a href="13_references.html#ref-RStudio-2020" role="doc-biblioref">Team’ 2020</a>)</span>.</p>
<p>Some R software packages used in this Chapter need to be installed so that the analyses can be done as shown there. The installation can be done in the following way:</p>
<p>The packages can then be loaded and made available in your R session.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="06_CaseStudy_ChirchikRiver.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(devtools)</span>
<span id="cb1-2"><a href="06_CaseStudy_ChirchikRiver.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="06_CaseStudy_ChirchikRiver.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)    </span>
<span id="cb1-4"><a href="06_CaseStudy_ChirchikRiver.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(timetk)       </span>
<span id="cb1-5"><a href="06_CaseStudy_ChirchikRiver.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DataExplorer) </span>
<span id="cb1-6"><a href="06_CaseStudy_ChirchikRiver.html#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(riversCentralAsia)</span></code></pre></div>
</div>
<div id="CaseStudyChirchikRiver" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> The Chirchik River Basin</h2>
<div id="overview" class="section level3" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Overview</h3>
<p>The Chirchik is a river in the Tashkent region of Uzbekistan and the biggest right tributary of the Syr Darya. The river is formed by the confluence of the Chatkal and the Pskem rivers in the Charvak reservoir. They emerge at the western end of the Tien Shan mountains in the border region of Kyrgyzstan, Kazakhstan and Uzbekistan. Below the Charvak hydroelectric power station, the river receives no more water from other tributaries and the water gets diverted in numerous canals. As part of the Chirchik-Bozsuu cascade, several dams along the river serve hydropower production and irrigation purposes.</p>
<div class="figure"><span id="fig:ChirchikRiverOverview"></span>
<img src="_bookdown_files/Chap6-Figures/ChirchikRiverBasin_Annotated_lr.jpg" alt="Overview over the Chirchik river basin with tributaries and the location of the main gauging stations in the zone of runoff formation and near the confluence with the Syr Darya." width="1866" />
<p class="caption">
Figure 4.1: Overview over the Chirchik river basin with tributaries and the location of the main gauging stations in the zone of runoff formation and near the confluence with the Syr Darya.
</p>
</div>
<p>Figure <a href="06_CaseStudy_ChirchikRiver.html#fig:ChirchikRiverOverview">4.1</a> shows a comprehensive overview of the Chirchik river basin and its tributaries as well as relevant modern gauging stations. Gauges are indicated with the semi-round shapes and the corresponding five digit official code as utilized by the Uzbek Hydrometeorological Service (HydroMet) indicated. The virtual gauge is not a real gauge in the sense that reservoir inflow is calculated from all contributing tributary flow components, i.e. Chatkal river, Pskem river, Nauvalisoy and Koksu Rivers.</p>
<p>Koksu however, with a basin area of 392 km<span class="math inline">\(^2\)</span>, is ungauged. So how does the HydroMet quantify its runoff contribution?</p>
</div>
<div id="discharge-estimation-in-ungauged-subcatchments" class="section level3" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Discharge Estimation in Ungauged Subcatchments</h3>
<p>Before the closure of the Charvak dam and the subsequent filling of the reservoir in and after 1974, the HydroMet experts started a detailed 3-years measurement comparison campaign at Charvak gauge and at gauge 16279 in Khudaydod (see Figure <a href="06_CaseStudy_ChirchikRiver.html#fig:ChirchikRiverOverview">4.1</a>). Both are located on Chatkal river. Charvak gauge had to be decommissioned after the closure of the dam because it got flooded.</p>
<p>The confluence of Koksu river with Charvak river is just upstream of the former Charvak gauge. Using daily data from the measurement comparisons campaign, the HydroMet experts could then relate Charvak gauge discharge to Khudaydod discharge using a linear relationship. At the same time, they were now able to relate Koksu discharge to the discharge at Chatkal River in Khudaydod in the following manner</p>
<p><span class="math display">\[
Q_{Koksu} \propto Q_{Charvak} - Q_{16279}
\]</span></p>
<p>We show the procedure here. After loading the <code>riversCentralAsia</code> Package as shown above, the relevant daily data from 01/01/1965 - 31/12/1967 can be loaded.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="06_CaseStudy_ChirchikRiver.html#cb2-1" aria-hidden="true" tabindex="-1"></a>KoksuDischarge <span class="co"># load Data</span></span></code></pre></div>
<pre><code>## # A tibble: 1,976 x 4
##    date        data code    units
##    &lt;date&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;
##  1 1965-01-01  35.6 Charvak m3/s 
##  2 1965-01-02  35.6 Charvak m3/s 
##  3 1965-01-03  33   Charvak m3/s 
##  4 1965-01-04  33   Charvak m3/s 
##  5 1965-01-05  33   Charvak m3/s 
##  6 1965-01-06  33   Charvak m3/s 
##  7 1965-01-07  34.3 Charvak m3/s 
##  8 1965-01-08  35.6 Charvak m3/s 
##  9 1965-01-09  38.4 Charvak m3/s 
## 10 1965-01-10  35.6 Charvak m3/s 
## # … with 1,966 more rows</code></pre>
<p>The data is stored in <em>long format</em>, meaning that measurements in time and for the two gauging stations are just stacked on top of each other in one long table. For the purpose here, we prefer the <em>wide format</em> where we have one date column with unique dates and then the data listed for each station in corresponding columns.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="06_CaseStudy_ChirchikRiver.html#cb4-1" aria-hidden="true" tabindex="-1"></a>KoksuDischarge_wide <span class="ot">&lt;-</span> KoksuDischarge <span class="sc">%&gt;%</span> <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> <span class="st">&#39;date&#39;</span>,<span class="at">values_from =</span> <span class="st">&#39;data&#39;</span>,<span class="at">names_from =</span> <span class="st">&quot;code&quot;</span>)</span>
<span id="cb4-2"><a href="06_CaseStudy_ChirchikRiver.html#cb4-2" aria-hidden="true" tabindex="-1"></a>KoksuDischarge_wide</span></code></pre></div>
<pre><code>## # A tibble: 988 x 3
##    date       Charvak `16279`
##    &lt;date&gt;       &lt;dbl&gt;   &lt;dbl&gt;
##  1 1965-01-01    35.6    33.4
##  2 1965-01-02    35.6    32.4
##  3 1965-01-03    33      30.4
##  4 1965-01-04    33      29.4
##  5 1965-01-05    33      30.4
##  6 1965-01-06    33      30.4
##  7 1965-01-07    34.3    31.4
##  8 1965-01-08    35.6    32.4
##  9 1965-01-09    38.4    34.4
## 10 1965-01-10    35.6    32.4
## # … with 978 more rows</code></pre>
<p>The runoff contribution of Koksu can be calculated in a simple manner.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="06_CaseStudy_ChirchikRiver.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding Koksu discharge to the dataframe</span></span>
<span id="cb6-2"><a href="06_CaseStudy_ChirchikRiver.html#cb6-2" aria-hidden="true" tabindex="-1"></a>KoksuDischarge_wide <span class="ot">&lt;-</span> KoksuDischarge_wide <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Koksu =</span> Charvak <span class="sc">-</span> <span class="st">`</span><span class="at">16279</span><span class="st">`</span>)</span>
<span id="cb6-3"><a href="06_CaseStudy_ChirchikRiver.html#cb6-3" aria-hidden="true" tabindex="-1"></a>KoksuDischarge_wide</span></code></pre></div>
<pre><code>## # A tibble: 988 x 4
##    date       Charvak `16279` Koksu
##    &lt;date&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1 1965-01-01    35.6    33.4  2.2 
##  2 1965-01-02    35.6    32.4  3.2 
##  3 1965-01-03    33      30.4  2.6 
##  4 1965-01-04    33      29.4  3.6 
##  5 1965-01-05    33      30.4  2.6 
##  6 1965-01-06    33      30.4  2.6 
##  7 1965-01-07    34.3    31.4  2.90
##  8 1965-01-08    35.6    32.4  3.2 
##  9 1965-01-09    38.4    34.4  4   
## 10 1965-01-10    35.6    32.4  3.2 
## # … with 978 more rows</code></pre>
<p>The relationship can now be visualized.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="06_CaseStudy_ChirchikRiver.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># and visualize</span></span>
<span id="cb8-2"><a href="06_CaseStudy_ChirchikRiver.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(KoksuDischarge_wide, <span class="fu">aes</span>(<span class="st">`</span><span class="at">16279</span><span class="st">`</span>, Koksu)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="06_CaseStudy_ChirchikRiver.html#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb8-4"><a href="06_CaseStudy_ChirchikRiver.html#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">bquote</span>(<span class="st">&#39;Discharge at Gauge 16279 Khudaydod in&#39;</span><span class="sc">~</span>m<span class="sc">^</span><span class="dv">3</span><span class="sc">/</span>s)) <span class="sc">+</span></span>
<span id="cb8-5"><a href="06_CaseStudy_ChirchikRiver.html#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span> (<span class="fu">bquote</span>(<span class="st">&#39;Koksu river discharge in&#39;</span><span class="sc">~</span>m<span class="sc">^</span><span class="dv">3</span><span class="sc">/</span>s))</span></code></pre></div>
<p><img src="applied-hydrological-modeling-central-asia_files/figure-html/unnamed-chunk-6-1.png" width="672" />
We can perform a linear regression to related discharge at Khudaydod to the one at Koksu. The coefficients of the linear regression can be obtained in the following way:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="06_CaseStudy_ChirchikRiver.html#cb9-1" aria-hidden="true" tabindex="-1"></a>lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Koksu <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> <span class="st">`</span><span class="at">16279</span><span class="st">`</span>,KoksuDischarge_wide)</span>
<span id="cb9-2"><a href="06_CaseStudy_ChirchikRiver.html#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Koksu ~ 0 + `16279`, data = KoksuDischarge_wide)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.295  -5.867  -1.918   1.416 120.419 
## 
## Coefficients:
##         Estimate Std. Error t value Pr(&gt;|t|)    
## `16279`  0.14469    0.00298   48.55   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.4 on 987 degrees of freedom
## Multiple R-squared:  0.7049, Adjusted R-squared:  0.7046 
## F-statistic:  2357 on 1 and 987 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Please note, in the specification of the linear model we add the 0 term to force the regression through the origin. Hence, the discharge of Koksu River can be estimated to be</p>
<p><span class="math display">\[
Q_{Koksu} = 0.145 * Q_{Khudaydod}
\]</span></p>
</div>
<div id="analysis-of-available-data" class="section level3" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Analysis of Available Data</h3>
<p>The <code>riversCentralAsia</code> Package provides available data of the gauging and meteorological stations in the Chirchik River Basin. Once this package is loaded, we are ready to start with data analysis.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="06_CaseStudy_ChirchikRiver.html#cb11-1" aria-hidden="true" tabindex="-1"></a>ChirchikRiverBasin <span class="co"># load data</span></span></code></pre></div>
<pre><code>## # A tibble: 29,244 x 14
##    date        data  norm units type  code  station river basin resolution lon_UTM42
##    &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt; &lt;fct&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt; &lt;fct&gt;          &lt;dbl&gt;
##  1 1932-01-10  48.8  38.8 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
##  2 1932-01-20  48.4  37.5 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
##  3 1932-01-31  42.4  36.6 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
##  4 1932-02-10  43.7  36.4 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
##  5 1932-02-20  44.2  36.3 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
##  6 1932-02-29  47.7  36.9 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
##  7 1932-03-10  54.1  39.4 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
##  8 1932-03-20  63.2  47.6 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
##  9 1932-03-31 103    60.5 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
## 10 1932-04-10 103    86.4 m3s   Q     16279 Khuday… Chat… Chir… dec           598278
## # … with 29,234 more rows, and 3 more variables: lat_UTM42 &lt;dbl&gt;, altitude_masl &lt;dbl&gt;,
## #   basinSize_sqkm &lt;dbl&gt;</code></pre>
<p>One can get more information about the data by typing <code>?ChirchikRiverBasin</code> in the console. Notice that, as above, the data are stored in <em>long format</em>. In other words, data from the individual stations is just stacked on top of each other. In this dataframe (called tibble in R), each row contains one time-stamped observation. Next to the data, the long-term discharge norm is stored in the tibble. The units of the data stored in the corresponding columns is stored and the data type (<em>Q</em> for discharge, <em>T</em> for temperature and <em>P</em> for precipitation). The station code is available as well as the station name, the river (subcatchment) and the basin name. In our case, the latter is always Chirchik. The column ‘res’ indicates the time resolution of the available data (either <em>dec</em> for 10-days decadal or <em>mon</em> for monthly). Finally, where known, the stations’ latitude and longitude, altitudes and the upstream basin size are given.</p>
<p>There are 7 discharge stations where <code>type = Q</code>. These are all unique stations as can be identified by their stations codes (see above in Figure <a href="06_CaseStudy_ChirchikRiver.html#fig:ChirchikRiverOverview">4.1</a> for the station locations).</p>
<p>We can generate timeseries plots of the river discharge data only by setting the corresponding station filter via <code>filter(type=='Q')</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="06_CaseStudy_ChirchikRiver.html#cb13-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> ChirchikRiverBasin</span>
<span id="cb13-2"><a href="06_CaseStudy_ChirchikRiver.html#cb13-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(type<span class="sc">==</span><span class="st">&#39;Q&#39;</span>) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(type,code,station,resolution) <span class="sc">%&gt;%</span> <span class="fu">plot_time_series</span>(date,data,<span class="at">.facet_ncol =</span> <span class="dv">2</span>,<span class="at">.interactive =</span> <span class="cn">FALSE</span>, <span class="at">.smooth =</span> <span class="cn">FALSE</span>, <span class="at">.title =</span> <span class="st">&#39;Available discharge data of Chirchik River Basin&#39;</span>)</span></code></pre></div>
<p><img src="applied-hydrological-modeling-central-asia_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The characteristics of the timeseries feature the typical snowmelt-driven runoff pattern with pronounced seasonality and interannual variability. At Chinaz near the confluence of the Chirchik River with the Syr Darya, however, a changing discharge regime can easily be identified over time. The drastic decrease in discharge there is due to two effects. First, in the 1960ies, the upstream irrigation greatly increased together with the interbasin water transfer. Second, the closure of the Charvak dam in 1974 and the subsequent filling of the dam decreased discharge during the filling period. Furthermore, the interannual variability of flows decreased from there onwards due to the now regulated flow regime. This latter effect is also visible at the Gazalkent gauge. The non-stationarity in the discharge timeseries at these stations is thus explained by anthropogenic effects.</p>
<p>Getting summary statistics of the gauged discharges allows us to quickly understand runoff contributions of the individual tributaries.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="06_CaseStudy_ChirchikRiver.html#cb14-1" aria-hidden="true" tabindex="-1"></a>data_stats <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(type <span class="sc">==</span> <span class="st">&#39;Q&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="06_CaseStudy_ChirchikRiver.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(date,data,code) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(code) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="06_CaseStudy_ChirchikRiver.html#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(data,<span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb14-4"><a href="06_CaseStudy_ChirchikRiver.html#cb14-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(data,<span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb14-5"><a href="06_CaseStudy_ChirchikRiver.html#cb14-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">max</span>(data,<span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb14-6"><a href="06_CaseStudy_ChirchikRiver.html#cb14-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(data,<span class="at">na.rm=</span><span class="cn">TRUE</span>),<span class="at">.groups =</span> <span class="st">&#39;keep&#39;</span>)</span>
<span id="cb14-7"><a href="06_CaseStudy_ChirchikRiver.html#cb14-7" aria-hidden="true" tabindex="-1"></a>data_stats <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## # A tibble: 7 x 5
##   code    mean   min    max     sd
##   &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 16279 116.    21.1  729   110.  
## 2 16290  79.4   12.7  438    69.3 
## 3 16924 205.    40.7 1231   183.  
## 4 16298   3.79   0.9   21.1   2.78
## 5 16300  22.4    3.9  114    19.3 
## 6 16275 105.     1.2  912   121.  
## 7 16262 229.    48.7 1220   186.</code></pre>
<p>The largest left tributary to Chirchik below the Charvak reservoir Aksak Ata. The gauging station on the river got dismantled a long time ago but an average long-term mean discharge of 2.35 m<span class="math inline">\(^{3}\)</span>/s is a solid estimated of its contribution to the overall discharge of Chirchik. Thus, if we add up long-term average discharge at Gazalkent and the one from Aksak Ata we obtain an annual norm discharge of 231 m<span class="math inline">\(^{3}\)</span>/s. With this, Chirchik river is the biggest right-tributary to the Syr Darya. Chatkal river contributes exactly half to it (115.7 m<span class="math inline">\(^{3}\)</span>/s) and Pskem river approximately one third (34.4% or 79.4 m<span class="math inline">\(^{3}\)</span>/s). Nauvalisoy is only a very small river with 1.6% runoff contribution (3.8 m<span class="math inline">\(^{3}\)</span>/s). From the available data, the long-term average runoff contribution by the ungauged Koksu river can be estimated to be 6.4 m<span class="math inline">\(^{3}\)</span>/s or 2.8%. Downstream of the reservoir, Ugam river contributes an additional 9.7% (22.4 m<span class="math inline">\(^{3}\)</span>/s) to the total flow.</p>
<p>Let us now turn our attention to the tributaries seasonality. We can easily investigate it using the <code>timetk</code> package function <code>plot_seasonal_diagnostics</code>. We exclude Chinaz gauge in our analysis for the above-mentioned reason that flow there is no longer representing a natural runoff regime. First, we plot the key gauged tributaries to the Charvak reservoir, i.e. Chatkal, Pskem and Nauvalisoy rivers.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="06_CaseStudy_ChirchikRiver.html#cb16-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(type<span class="sc">==</span><span class="st">&#39;Q&#39;</span>,code<span class="sc">!=</span><span class="st">&#39;16275&#39;</span>,code<span class="sc">!=</span><span class="st">&#39;16294&#39;</span>,code<span class="sc">!=</span><span class="st">&#39;16300&#39;</span>,code<span class="sc">!=</span><span class="st">&#39;16262&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="06_CaseStudy_ChirchikRiver.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(date,data,code) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="06_CaseStudy_ChirchikRiver.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(code) <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="06_CaseStudy_ChirchikRiver.html#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_seasonal_diagnostics</span>(<span class="at">.date_var =</span> date,<span class="at">.value =</span> data,<span class="at">.interactive =</span> <span class="cn">FALSE</span>,<span class="at">.feature_set =</span> <span class="fu">c</span>(<span class="st">&quot;week&quot;</span>,<span class="st">&quot;month.lbl&quot;</span>))</span></code></pre></div>
<p><img src="applied-hydrological-modeling-central-asia_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The seasonality with the spring and summer runoff peaks is striking in all three rivers. Nauvalisoy discharge peaks, on average, during or around week 20. Chatkal river discharge peaks around week 23 and Pskem river around week 26. These differences can be explained with the different mean catchment elevations where Nauvalisoy is the lowest lying and Pskem catchment the highest catchment (see also Chapter <a href="04_Hydrological_Systems.html#HydrologicalSystems">2</a> for more information).</p>
<p>Discharge seasonality of the gauging stations downstream of Charvak reservoir is shown below. Note that we only have monthly values for these stations and are thus only showing the monthly seasonality panels.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="06_CaseStudy_ChirchikRiver.html#cb17-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(type<span class="sc">==</span><span class="st">&#39;Q&#39;</span>,code<span class="sc">!=</span><span class="st">&#39;16279&#39;</span>,code<span class="sc">!=</span><span class="st">&#39;16298&#39;</span>,code<span class="sc">!=</span><span class="st">&#39;16290&#39;</span>,code<span class="sc">!=</span><span class="st">&#39;16294&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="06_CaseStudy_ChirchikRiver.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(date,data,code) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="06_CaseStudy_ChirchikRiver.html#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(code) <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="06_CaseStudy_ChirchikRiver.html#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_seasonal_diagnostics</span>(<span class="at">.date_var =</span> date,<span class="at">.value =</span> data,<span class="at">.interactive =</span> <span class="cn">FALSE</span>,<span class="at">.feature_set =</span> <span class="fu">c</span>(<span class="st">&quot;month.lbl&quot;</span>))</span></code></pre></div>
<p><img src="applied-hydrological-modeling-central-asia_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>==== We can also visualize the summary statistics. However, since the data span several order of magnitudes, we choose to display the <code>log()</code> of the discharge data.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="06_CaseStudy_ChirchikRiver.html#cb18-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="06_CaseStudy_ChirchikRiver.html#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(type <span class="sc">==</span> <span class="st">&#39;Q&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="06_CaseStudy_ChirchikRiver.html#cb18-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(data,code) <span class="sc">%&gt;%</span> </span>
<span id="cb18-4"><a href="06_CaseStudy_ChirchikRiver.html#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(code)</span>
<span id="cb18-5"><a href="06_CaseStudy_ChirchikRiver.html#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="06_CaseStudy_ChirchikRiver.html#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(p, <span class="fu">aes</span>(<span class="at">x =</span> code, <span class="at">y =</span> data <span class="sc">%&gt;%</span> <span class="fu">log</span>())) <span class="sc">+</span> </span>
<span id="cb18-7"><a href="06_CaseStudy_ChirchikRiver.html#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb18-8"><a href="06_CaseStudy_ChirchikRiver.html#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Gauging Station&#39;</span>, <span class="at">y =</span> <span class="fu">bquote</span>(<span class="st">&#39;Discharge in&#39;</span><span class="sc">~</span>m<span class="sc">^</span><span class="dv">3</span><span class="sc">/</span>s))</span></code></pre></div>
<p><img src="applied-hydrological-modeling-central-asia_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="05_Irrigation_CentralAsia.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="07_PII_Retrieval_Analysis_Geo_Hydro_Data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/06_CaseStudy_ChirchikRiver.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["applied-hydrological-modeling-central-asia.pdf", "applied-hydrological-modeling-central-asia.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
