<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.4 Data on Climate Projections | Applied Modeling of Hydrological Systems in Central Asia</title>
  <meta name="description" content="This is a open-source course book on Central Asia hydrological systems and hydrological modeling." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="3.4 Data on Climate Projections | Applied Modeling of Hydrological Systems in Central Asia" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a open-source course book on Central Asia hydrological systems and hydrological modeling." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.4 Data on Climate Projections | Applied Modeling of Hydrological Systems in Central Asia" />
  
  <meta name="twitter:description" content="This is a open-source course book on Central Asia hydrological systems and hydrological modeling." />
  

<meta name="author" content="Tobias Siegfried and Beatrice Marti" />


<meta name="date" content="2021-04-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="Data-ClimateReanalysisData.html"/>
<link rel="next" href="snow-cover-data.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Hydrological Modeling</a></li>

<li class="divider"></li>
<li><a href="index.html#Welcome"></a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i>Foreword</a>
<ul>
<li class="chapter" data-level="" data-path="day-1-introduction-and-installation-of-software.html"><a href="day-1-introduction-and-installation-of-software.html"><i class="fa fa-check"></i>Day 1: Introduction and installation of software</a></li>
<li class="chapter" data-level="" data-path="day-2-catchment-characterization.html"><a href="day-2-catchment-characterization.html"><i class="fa fa-check"></i>Day 2: Catchment characterization</a></li>
<li class="chapter" data-level="" data-path="day-3-geospatial-data-and-introduction-to-linear-reservoir-models.html"><a href="day-3-geospatial-data-and-introduction-to-linear-reservoir-models.html"><i class="fa fa-check"></i>Day 3: Geospatial data and introduction to linear reservoir models</a></li>
<li class="chapter" data-level="" data-path="day-4-discussion-of-types-of-hydrological-models.html"><a href="day-4-discussion-of-types-of-hydrological-models.html"><i class="fa fa-check"></i>Day 4: Discussion of types of hydrological models</a></li>
<li class="chapter" data-level="" data-path="day-5-the-hbv-model.html"><a href="day-5-the-hbv-model.html"><i class="fa fa-check"></i>Day 5: The HBV model</a></li>
<li class="chapter" data-level="" data-path="day-6-model-calibration-and-validation.html"><a href="day-6-model-calibration-and-validation.html"><i class="fa fa-check"></i>Day 6: Model calibration and validation</a></li>
<li class="chapter" data-level="0.1" data-path="day-7-case-studies.html"><a href="day-7-case-studies.html"><i class="fa fa-check"></i><b>0.1</b> Day 7: Case studies</a></li>
<li class="chapter" data-level="0.2" data-path="day-8-real-world-applications.html"><a href="day-8-real-world-applications.html"><i class="fa fa-check"></i><b>0.2</b> Day 8: Real-world applications</a></li>
<li class="chapter" data-level="0.3" data-path="day-9-student-presentations-and-wrap-up-of-workshop.html"><a href="day-9-student-presentations-and-wrap-up-of-workshop.html"><i class="fa fa-check"></i><b>0.3</b> Day 9: Student presentations and wrap-up of workshop</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#Part1_Hydrological_Systems"><i class="fa fa-check"></i>(PART) Part I Hydrological Systems</a>
<ul>
<li class="chapter" data-level="0.4" data-path="TamingHydrologicalSystems.html"><a href="TamingHydrologicalSystems.html"><i class="fa fa-check"></i><b>0.4</b> The Taming of the Central Asian Rivers</a></li>
<li class="chapter" data-level="0.5" data-path="PostTransitionDevelopmentsChallenges.html"><a href="PostTransitionDevelopmentsChallenges.html"><i class="fa fa-check"></i><b>0.5</b> Post-Transition Development and Challenges</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="HydrologicalSystems.html"><a href="HydrologicalSystems.html"><i class="fa fa-check"></i><b>1</b> Hydrological Systems in Central Asia</a>
<ul>
<li class="chapter" data-level="1.1" data-path="regional-hydro-climatological-features.html"><a href="regional-hydro-climatological-features.html"><i class="fa fa-check"></i><b>1.1</b> Regional Hydro-Climatological Features</a></li>
<li class="chapter" data-level="1.2" data-path="chap-regionalWaterBalance.html"><a href="chap-regionalWaterBalance.html"><i class="fa fa-check"></i><b>1.2</b> Regional Water Balance</a></li>
<li class="chapter" data-level="1.3" data-path="runoff-formation.html"><a href="runoff-formation.html"><i class="fa fa-check"></i><b>1.3</b> Runoff Formation</a></li>
<li class="chapter" data-level="1.4" data-path="average-multi-year-runoff.html"><a href="average-multi-year-runoff.html"><i class="fa fa-check"></i><b>1.4</b> Average Multi-Year Runoff</a></li>
<li class="chapter" data-level="1.5" data-path="annual-runoff-fluctuations.html"><a href="annual-runoff-fluctuations.html"><i class="fa fa-check"></i><b>1.5</b> Annual Runoff Fluctuations</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="CaseStudies.html"><a href="CaseStudies.html"><i class="fa fa-check"></i><b>2</b> Case Studies</a>
<ul>
<li class="chapter" data-level="2.1" data-path="GuntRB.html"><a href="GuntRB.html"><i class="fa fa-check"></i><b>2.1</b> Gunt River Basin</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="GuntRB.html"><a href="GuntRB.html#GuntRBOverview"><i class="fa fa-check"></i><b>2.1.1</b> Basin Characterization</a></li>
<li class="chapter" data-level="2.1.2" data-path="GuntRB.html"><a href="GuntRB.html#GuntHyrology"><i class="fa fa-check"></i><b>2.1.2</b> Hydrology</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="CRB.html"><a href="CRB.html"><i class="fa fa-check"></i><b>2.2</b> Chirchik River Basin</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="CRB.html"><a href="CRB.html#CRBOverview"><i class="fa fa-check"></i><b>2.2.1</b> Basin Characterization</a></li>
<li class="chapter" data-level="2.2.2" data-path="CRB.html"><a href="CRB.html#CRBBasinCharacteristics"><i class="fa fa-check"></i><b>2.2.2</b> Hydrology</a></li>
<li class="chapter" data-level="2.2.3" data-path="CRB.html"><a href="CRB.html#CRB_KoskuDischargeContribution"><i class="fa fa-check"></i><b>2.2.3</b> Discharge Estimation from the Ungauged Kosku Tributary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#Part2-Applied-Modeling"><i class="fa fa-check"></i>(PART) Part II Applied Modeling</a>
<ul>
<li class="chapter" data-level="2.3" data-path="derivation-of-the-budyko-relationship.html"><a href="derivation-of-the-budyko-relationship.html"><i class="fa fa-check"></i><b>2.3</b> Derivation of the Budyko Relationship</a></li>
<li class="chapter" data-level="2.4" data-path="effects-of-snow-ratio-on-annual-runoff-within-the-budyko-framework.html"><a href="effects-of-snow-ratio-on-annual-runoff-within-the-budyko-framework.html"><i class="fa fa-check"></i><b>2.4</b> Effects of Snow Ratio on Annual Runoff within the Budyko Framework</a></li>
<li class="chapter" data-level="2.5" data-path="hydrological-response-to-a-changing-climate.html"><a href="hydrological-response-to-a-changing-climate.html"><i class="fa fa-check"></i><b>2.5</b> Hydrological Response to a Changing Climate</a></li>
<li class="chapter" data-level="2.6" data-path="application-to-central-asian-river-basins.html"><a href="application-to-central-asian-river-basins.html"><i class="fa fa-check"></i><b>2.6</b> Application to Central Asian River Basins</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="application-to-central-asian-river-basins.html"><a href="application-to-central-asian-river-basins.html#data"><i class="fa fa-check"></i><b>2.6.1</b> Data</a></li>
<li class="chapter" data-level="2.6.2" data-path="application-to-central-asian-river-basins.html"><a href="application-to-central-asian-river-basins.html#model"><i class="fa fa-check"></i><b>2.6.2</b> Model</a></li>
<li class="chapter" data-level="2.6.3" data-path="application-to-central-asian-river-basins.html"><a href="application-to-central-asian-river-basins.html#conclusions"><i class="fa fa-check"></i><b>2.6.3</b> Conclusions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Chapter-DATA.html"><a href="Chapter-DATA.html"><i class="fa fa-check"></i><b>3</b> Data Retrieval, Preparation &amp; Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="Data-StationData.html"><a href="Data-StationData.html"><i class="fa fa-check"></i><b>3.1</b> Station Data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="Data-StationData.html"><a href="Data-StationData.html#AvailableData"><i class="fa fa-check"></i><b>3.1.1</b> Available Data</a></li>
<li class="chapter" data-level="3.1.2" data-path="Data-StationData.html"><a href="Data-StationData.html#StationData::GapFilling"><i class="fa fa-check"></i><b>3.1.2</b> Gap Filling Discharge Data</a></li>
<li class="chapter" data-level="3.1.3" data-path="Data-StationData.html"><a href="Data-StationData.html#DataPreparationPT"><i class="fa fa-check"></i><b>3.1.3</b> Gap Filling Meteorological Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="Data-StationData.html"><a href="Data-StationData.html#AnomaliesOutliers"><i class="fa fa-check"></i><b>3.1.4</b> Anomalies and Outliers</a></li>
<li class="chapter" data-level="3.1.5" data-path="Data-StationData.html"><a href="Data-StationData.html#FinalData"><i class="fa fa-check"></i><b>3.1.5</b> Putting it all together</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="Data-GeospatialData.html"><a href="Data-GeospatialData.html"><i class="fa fa-check"></i><b>3.2</b> Geospatial Data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="Data-GeospatialData.html"><a href="Data-GeospatialData.html#prerequisites"><i class="fa fa-check"></i><b>3.2.1</b> Prerequisites</a></li>
<li class="chapter" data-level="3.2.2" data-path="Data-GeospatialData.html"><a href="Data-GeospatialData.html#section-geospatial-data-steps-setting-up"><i class="fa fa-check"></i><b>3.2.2</b> Setting up QGIS</a></li>
<li class="chapter" data-level="3.2.3" data-path="Data-GeospatialData.html"><a href="Data-GeospatialData.html#section-geospatial-data-load-dem"><i class="fa fa-check"></i><b>3.2.3</b> Load DEM</a></li>
<li class="chapter" data-level="3.2.4" data-path="Data-GeospatialData.html"><a href="Data-GeospatialData.html#section-steps-derive-catchment-boundaries"><i class="fa fa-check"></i><b>3.2.4</b> Catchment delineation</a></li>
<li class="chapter" data-level="3.2.5" data-path="Data-GeospatialData.html"><a href="Data-GeospatialData.html#run-through-the-process-model"><i class="fa fa-check"></i><b>3.2.5</b> Run through the process model</a></li>
<li class="chapter" data-level="3.2.6" data-path="Data-GeospatialData.html"><a href="Data-GeospatialData.html#manually-edit-the-gis-layers-for-import-in-rs-minerve"><i class="fa fa-check"></i><b>3.2.6</b> Manually edit the GIS Layers for import in RS MINERVE</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="Data-ClimateReanalysisData.html"><a href="Data-ClimateReanalysisData.html"><i class="fa fa-check"></i><b>3.3</b> Climate Reanalysis Data</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="Data-ClimateReanalysisData.html"><a href="Data-ClimateReanalysisData.html#Data::CHELSA"><i class="fa fa-check"></i><b>3.3.1</b> CHELSA V1.2.1 Data and Bias Correction</a></li>
<li class="chapter" data-level="3.3.2" data-path="Data-ClimateReanalysisData.html"><a href="Data-ClimateReanalysisData.html#Data::ERA5"><i class="fa fa-check"></i><b>3.3.2</b> ERA5 Download and Data Resampling with PBCORR CHELSA</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-on-climate-projections.html"><a href="data-on-climate-projections.html"><i class="fa fa-check"></i><b>3.4</b> Data on Climate Projections</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="data-on-climate-projections.html"><a href="data-on-climate-projections.html#CHELSA21Century"><i class="fa fa-check"></i><b>3.4.1</b> High Res. Monthly Climate Time Series for 2006 - 2100</a></li>
<li class="chapter" data-level="3.4.2" data-path="data-on-climate-projections.html"><a href="data-on-climate-projections.html#Data::WeatherGenerator"><i class="fa fa-check"></i><b>3.4.2</b> Using a Weather Generator to Simulate Daily Future Climate</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="snow-cover-data.html"><a href="snow-cover-data.html"><i class="fa fa-check"></i><b>3.5</b> Snow Cover Data</a></li>
<li class="chapter" data-level="3.6" data-path="glacier-data.html"><a href="glacier-data.html"><i class="fa fa-check"></i><b>3.6</b> Glacier Data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="RSMinerveMODELS.html"><a href="RSMinerveMODELS.html"><i class="fa fa-check"></i><b>4</b> Hydrological-Hydraulic Modeling</a>
<ul>
<li class="chapter" data-level="4.1" data-path="section-rsminerve-prerequisites.html"><a href="section-rsminerve-prerequisites.html"><i class="fa fa-check"></i><b>4.1</b> Prerequisites</a></li>
<li class="chapter" data-level="4.2" data-path="section-rsminerve-why-model-introduction.html"><a href="section-rsminerve-why-model-introduction.html"><i class="fa fa-check"></i><b>4.2</b> Recap: Hydrological response</a></li>
<li class="chapter" data-level="4.3" data-path="section-general-modelling-process.html"><a href="section-general-modelling-process.html"><i class="fa fa-check"></i><b>4.3</b> Recap: The general modeling process</a></li>
<li class="chapter" data-level="4.4" data-path="section-rsminerve-data-preparation.html"><a href="section-rsminerve-data-preparation.html"><i class="fa fa-check"></i><b>4.4</b> Data Preparation and Setup</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="section-rsminerve-data-preparation.html"><a href="section-rsminerve-data-preparation.html#examining-and-understanding-the-gis-data"><i class="fa fa-check"></i><b>4.4.1</b> Examining and Understanding the GIS Data</a></li>
<li class="chapter" data-level="4.4.2" data-path="section-rsminerve-data-preparation.html"><a href="section-rsminerve-data-preparation.html#loading-gis-data-and-model-creation"><i class="fa fa-check"></i><b>4.4.2</b> Loading GIS Data and Model Creation</a></li>
<li class="chapter" data-level="4.4.3" data-path="section-rsminerve-data-preparation.html"><a href="section-rsminerve-data-preparation.html#climate-data"><i class="fa fa-check"></i><b>4.4.3</b> Climate Data</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="section-hbv-model.html"><a href="section-hbv-model.html"><i class="fa fa-check"></i><b>4.5</b> The HBV model</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="section-hbv-model.html"><a href="section-hbv-model.html#section-hbv-nauvalisoy-tutorial-short"><i class="fa fa-check"></i><b>4.5.1</b> HBV example: Simple model of the Nauvalisoy river catchment</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="section-model-calibration-and-validation.html"><a href="section-model-calibration-and-validation.html"><i class="fa fa-check"></i><b>4.6</b> Model Calibration and Validation</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="section-model-calibration-and-validation.html"><a href="section-model-calibration-and-validation.html#section-calibration-principles"><i class="fa fa-check"></i><b>4.6.1</b> Basic Principles</a></li>
<li class="chapter" data-level="4.6.2" data-path="section-model-calibration-and-validation.html"><a href="section-model-calibration-and-validation.html#secion-calibration-practical-steps"><i class="fa fa-check"></i><b>4.6.2</b> Practical Steps</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="application-investigating-climate-change-impacts.html"><a href="application-investigating-climate-change-impacts.html"><i class="fa fa-check"></i><b>4.7</b> Application: Investigating Climate Change Impacts</a></li>
<li class="chapter" data-level="4.8" data-path="discussion.html"><a href="discussion.html"><i class="fa fa-check"></i><b>4.8</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="HydroModelsEmpiricalModels.html"><a href="HydroModelsEmpiricalModels.html"><i class="fa fa-check"></i><b>5</b> Discharge Forecasting with Predictive Inference</a>
<ul>
<li class="chapter" data-level="" data-path="prerequisites-1.html"><a href="prerequisites-1.html"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="5.1" data-path="Chap9PredictiveInference.html"><a href="Chap9PredictiveInference.html"><i class="fa fa-check"></i><b>5.1</b> Forecasting Using Predictive Inference</a></li>
<li class="chapter" data-level="5.2" data-path="forecasting-in-the-central-asian-hydromets.html"><a href="forecasting-in-the-central-asian-hydromets.html"><i class="fa fa-check"></i><b>5.2</b> Forecasting in the Central Asian Hydromets</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="forecasting-in-the-central-asian-hydromets.html"><a href="forecasting-in-the-central-asian-hydromets.html#background"><i class="fa fa-check"></i><b>5.2.1</b> Background</a></li>
<li class="chapter" data-level="5.2.2" data-path="forecasting-in-the-central-asian-hydromets.html"><a href="forecasting-in-the-central-asian-hydromets.html#forecasting-for-what-and-whom"><i class="fa fa-check"></i><b>5.2.2</b> Forecasting for What and Whom?</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="Chap9DataPreparation.html"><a href="Chap9DataPreparation.html"><i class="fa fa-check"></i><b>5.3</b> Data and Preparation</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="Chap9DataPreparation.html"><a href="Chap9DataPreparation.html#Chap9AvailableData"><i class="fa fa-check"></i><b>5.3.1</b> Available Data</a></li>
<li class="chapter" data-level="5.3.2" data-path="Chap9DataPreparation.html"><a href="Chap9DataPreparation.html#Chap9DataPreparationQ"><i class="fa fa-check"></i><b>5.3.2</b> Gap Filling Discharge Data</a></li>
<li class="chapter" data-level="5.3.3" data-path="Chap9DataPreparation.html"><a href="Chap9DataPreparation.html#Chap9DataPreparationPT"><i class="fa fa-check"></i><b>5.3.3</b> Gap Filling Meteorological Data</a></li>
<li class="chapter" data-level="5.3.4" data-path="Chap9DataPreparation.html"><a href="Chap9DataPreparation.html#Chap9AnomaliesOutliers"><i class="fa fa-check"></i><b>5.3.4</b> Anomalies and Outliers</a></li>
<li class="chapter" data-level="5.3.5" data-path="Chap9DataPreparation.html"><a href="Chap9DataPreparation.html#Chap9_FinalData"><i class="fa fa-check"></i><b>5.3.5</b> Putting it all together</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="Chap9-DataAnalysis.html"><a href="Chap9-DataAnalysis.html"><i class="fa fa-check"></i><b>5.4</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="Chap9-DataAnalysis.html"><a href="Chap9-DataAnalysis.html#Chap_9_DataTransformation"><i class="fa fa-check"></i><b>5.4.1</b> Data Transformation</a></li>
<li class="chapter" data-level="5.4.2" data-path="Chap9-DataAnalysis.html"><a href="Chap9-DataAnalysis.html#Chap9_Trends"><i class="fa fa-check"></i><b>5.4.2</b> Detecting Trends</a></li>
<li class="chapter" data-level="5.4.3" data-path="Chap9-DataAnalysis.html"><a href="Chap9-DataAnalysis.html#Chap9_Autocorrelations"><i class="fa fa-check"></i><b>5.4.3</b> Auto- and Crosscorrelations</a></li>
<li class="chapter" data-level="5.4.4" data-path="Chap9-DataAnalysis.html"><a href="Chap9-DataAnalysis.html#Chap9_SeasonalityAnalysis"><i class="fa fa-check"></i><b>5.4.4</b> Time Series Seasonality</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="Chap9FeatureEngineering.html"><a href="Chap9FeatureEngineering.html"><i class="fa fa-check"></i><b>5.5</b> Investigating and Engineering Predictors</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="Chap9FeatureEngineering.html"><a href="Chap9FeatureEngineering.html#Chap9_CurrentPractice"><i class="fa fa-check"></i><b>5.5.1</b> Benchmark: Current Operational Forecasting Models in the Hydrometeorological Agencies</a></li>
<li class="chapter" data-level="5.5.2" data-path="Chap9FeatureEngineering.html"><a href="Chap9FeatureEngineering.html#Chap9_TSR"><i class="fa fa-check"></i><b>5.5.2</b> Time Series Regression Models</a></li>
<li class="chapter" data-level="5.5.3" data-path="Chap9FeatureEngineering.html"><a href="Chap9FeatureEngineering.html#Chap9_ForecastQuality"><i class="fa fa-check"></i><b>5.5.3</b> Assessing the Quality of Forecasts</a></li>
<li class="chapter" data-level="5.5.4" data-path="Chap9FeatureEngineering.html"><a href="Chap9FeatureEngineering.html#generating-and-assessing-out-of-sample-forecasts"><i class="fa fa-check"></i><b>5.5.4</b> Generating and Assessing Out-of-Sample Forecasts</a></li>
<li class="chapter" data-level="5.5.5" data-path="Chap9FeatureEngineering.html"><a href="Chap9FeatureEngineering.html#Chap9_MLM"><i class="fa fa-check"></i><b>5.5.5</b> Machine Learning Models</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="save-data-for-hot-start.html"><a href="save-data-for-hot-start.html"><i class="fa fa-check"></i><b>5.6</b> Save Data for Hot Start</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="Operationalization.html"><a href="Operationalization.html"><i class="fa fa-check"></i><b>6</b> Operationalization of Models - Opportunities and Challenges</a>
<ul>
<li class="chapter" data-level="6.1" data-path="co-design-phase.html"><a href="co-design-phase.html"><i class="fa fa-check"></i><b>6.1</b> Co-design Phase</a></li>
<li class="chapter" data-level="6.2" data-path="modeling-phase.html"><a href="modeling-phase.html"><i class="fa fa-check"></i><b>6.2</b> Modeling Phase</a></li>
<li class="chapter" data-level="6.3" data-path="testing-phase.html"><a href="testing-phase.html"><i class="fa fa-check"></i><b>6.3</b> Testing Phase</a></li>
<li class="chapter" data-level="6.4" data-path="operational-deployment.html"><a href="operational-deployment.html"><i class="fa fa-check"></i><b>6.4</b> Operational Deployment</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ChapterAppendix.html"><a href="ChapterAppendix.html"><i class="fa fa-check"></i><b>7</b> (APPENDIX) Appendix</a>
<ul>
<li class="chapter" data-level="7.1" data-path="section-appendix-open-source-resources.html"><a href="section-appendix-open-source-resources.html"><i class="fa fa-check"></i><b>7.1</b> Appendix A: Open-source resources</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="section-appendix-open-source-resources.html"><a href="section-appendix-open-source-resources.html#literature"><i class="fa fa-check"></i><b>7.1.1</b> Literature</a></li>
<li class="chapter" data-level="7.1.2" data-path="section-appendix-open-source-resources.html"><a href="section-appendix-open-source-resources.html#section-open-resrouces-software-QGIS"><i class="fa fa-check"></i><b>7.1.2</b> QGIS</a></li>
<li class="chapter" data-level="7.1.3" data-path="section-appendix-open-source-resources.html"><a href="section-appendix-open-source-resources.html#section-open-resrouces-software-R"><i class="fa fa-check"></i><b>7.1.3</b> R and RStudio</a></li>
<li class="chapter" data-level="7.1.4" data-path="section-appendix-open-source-resources.html"><a href="section-appendix-open-source-resources.html#section-open-resrouces-software-RSMinerve"><i class="fa fa-check"></i><b>7.1.4</b> RS Minerve</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html"><i class="fa fa-check"></i><b>7.2</b> Appendix B: Quick Guides</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-register-with-earth-explorer"><i class="fa fa-check"></i><b>7.2.1</b> EE: Register for an account</a></li>
<li class="chapter" data-level="7.2.2" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-earth-explorer-download-srtm"><i class="fa fa-check"></i><b>7.2.2</b> EE: Download SRTM data for a selected region</a></li>
<li class="chapter" data-level="7.2.3" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-qgis-window-overview"><i class="fa fa-check"></i><b>7.2.3</b> The QGIS window - overview</a></li>
<li class="chapter" data-level="7.2.4" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-saving-a-new-qgis-project"><i class="fa fa-check"></i><b>7.2.4</b> QGIS: Saving a new QGIS project</a></li>
<li class="chapter" data-level="7.2.5" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-change-project-projection-qgis"><i class="fa fa-check"></i><b>7.2.5</b> QGIS: Change the projection of the QGIS project</a></li>
<li class="chapter" data-level="7.2.6" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-install-and-activate-plugins-in-QGIS3"><i class="fa fa-check"></i><b>7.2.6</b> QGIS: Install and activate plugins in QGIS3</a></li>
<li class="chapter" data-level="7.2.7" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-managing-panels"><i class="fa fa-check"></i><b>7.2.7</b> GQIS: Managing panels visibility in QGIS</a></li>
<li class="chapter" data-level="7.2.8" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-loading-public-background-layers"><i class="fa fa-check"></i><b>7.2.8</b> QGIS: Loading public background maps</a></li>
<li class="chapter" data-level="7.2.9" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-zoom-to-layer"><i class="fa fa-check"></i><b>7.2.9</b> QGIS: Zoom to layer</a></li>
<li class="chapter" data-level="7.2.10" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-srtm-plugin"><i class="fa fa-check"></i><b>7.2.10</b> QGIS: Import SRTM layers using the SRTM plugin</a></li>
<li class="chapter" data-level="7.2.11" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-merge-srtm-tiles"><i class="fa fa-check"></i><b>7.2.11</b> QGIS: Merge SRTM tiles to a single layer</a></li>
<li class="chapter" data-level="7.2.12" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-add-vector-layer-to-qgis"><i class="fa fa-check"></i><b>7.2.12</b> Add vector layer to QGIS</a></li>
<li class="chapter" data-level="7.2.13" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-change-color-of-vector-layer"><i class="fa fa-check"></i><b>7.2.13</b> Change color of a vector layer</a></li>
<li class="chapter" data-level="7.2.14" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-quickguides-create-hbv-model"><i class="fa fa-check"></i><b>7.2.14</b> RSM: Create HBV model and edit parameters</a></li>
<li class="chapter" data-level="7.2.15" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-quickguides-add-climate-station"><i class="fa fa-check"></i><b>7.2.15</b> RSM: Add and link climate station</a></li>
<li class="chapter" data-level="7.2.16" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-quickguides-import-climate-data"><i class="fa fa-check"></i><b>7.2.16</b> RSM: Import climate data</a></li>
<li class="chapter" data-level="7.2.17" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-quickguides-atapt-model-settings"><i class="fa fa-check"></i><b>7.2.17</b> RSM: Adapt model settings</a></li>
<li class="chapter" data-level="7.2.18" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-export-sim-results-to-db"><i class="fa fa-check"></i><b>7.2.18</b> RSM: Export simulation results to data base</a></li>
<li class="chapter" data-level="7.2.19" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-quickguides-add-comparator-and-discharge-data"><i class="fa fa-check"></i><b>7.2.19</b> RSM: Add comparator and load discharge measurements</a></li>
<li class="chapter" data-level="7.2.20" data-path="appendix-b-quick-guides.html"><a href="appendix-b-quick-guides.html#section-quickguides-copy-paste-database-values"><i class="fa fa-check"></i><b>7.2.20</b> RSM: Copy-paste data to database</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="appendix-c-processing-climate-data.html"><a href="appendix-c-processing-climate-data.html"><i class="fa fa-check"></i><b>7.3</b> Appendix C: Processing Climate Data</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="appendix-c-processing-climate-data.html"><a href="appendix-c-processing-climate-data.html#cutting-chelsa-v.1.2.1-to-ca-domain"><i class="fa fa-check"></i><b>7.3.1</b> Cutting CHELSA v.1.2.1 to CA Domain</a></li>
<li class="chapter" data-level="7.3.2" data-path="appendix-c-processing-climate-data.html"><a href="appendix-c-processing-climate-data.html#bias-correcting-chelsa-v1.2.1-precipitation-data-for-snow-undercatch"><i class="fa fa-check"></i><b>7.3.2</b> Bias Correcting CHELSA v1.2.1 Precipitation Data for Snow Undercatch</a></li>
<li class="chapter" data-level="7.3.3" data-path="appendix-c-processing-climate-data.html"><a href="appendix-c-processing-climate-data.html#computing-mean-monthly-temperature-climatology-from-chelsa-v1.2.1-data"><i class="fa fa-check"></i><b>7.3.3</b> Computing Mean Monthly Temperature Climatology from CHELSA v1.2.1 data</a></li>
<li class="chapter" data-level="7.3.4" data-path="appendix-c-processing-climate-data.html"><a href="appendix-c-processing-climate-data.html#era5"><i class="fa fa-check"></i><b>7.3.4</b> ERA5</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sectin-appendix-solutions.html"><a href="sectin-appendix-solutions.html"><i class="fa fa-check"></i><b>7.4</b> Appendix D: Solutions to exercises</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="sectin-appendix-solutions.html"><a href="sectin-appendix-solutions.html#section-appendix-solutions-exercise1"><i class="fa fa-check"></i><b>7.4.1</b> Exercise on Linear Reservoir modelling</a></li>
<li class="chapter" data-level="7.4.2" data-path="sectin-appendix-solutions.html"><a href="sectin-appendix-solutions.html#section-appendix-solutions-hbv-exercises"><i class="fa fa-check"></i><b>7.4.2</b> Exercises on the HBV model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="References.html"><a href="References.html"><i class="fa fa-check"></i><b>8</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Modeling of Hydrological Systems in Central Asia</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-on-climate-projections" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Data on Climate Projections</h2>
<p>In order to look into the future with a hydrological model for exploring climate scenarios, it needs to be fed with those scenarios. The production of these scenarios in a way resembles the steps described for the reanalysis data but also differs in some marked way. Let us outline them first before diving into the details.</p>
<p>First, a baseline period is defined which serves as a reference against which future climate impacts are assessed. Second, the future period of interest for the investigation of climate impacts needs to be defined and climate scenarios identified that cover the area and period of interest. The future climate scenarios are outputs from global climate models (GCMs). These GCMs normally generate monthly data as a function of representative concentration pathways (called RCPs). They describe possible futures as a function of different atmospheric CO<sub>2</sub>-concentration scenarios.</p>
<p>We focus the discussion here on the RCP 4.5 and RCP 8.5 concentration scenarios. According to the IPCC, RCP 4.5 is an intermediate scenario where CO<sub>2</sub> emissions peak around 2040, then decline. Compared to this, RCP 8.5 is generally considered to be a worst case climate change scenario. Very detailed information regarding these scenarios, their underlying assumptions and assumptions can be found on the dedicated website served by the Intergovernmental Panel for Climate Change (IPCC). See the link <a href="https://ar5-syr.ipcc.ch/topic_futurechanges.php">here</a>.</p>
<div class="figure"><span id="fig:rcpGGConcetrationLevels"></span>
<img src="_bookdown_files/FIG_DATA/greenhouseGasConcetrations_RCP.jpg" alt="The development of greenhouse gas concentrations during the 21st century as a function of the corresponding scenario. We focus here on RCP4.5 and RCP8.5. Source: [@van_Vuuren_2011]" width="1180" />
<p class="caption">
Figure 3.49: The development of greenhouse gas concentrations during the 21st century as a function of the corresponding scenario. We focus here on RCP4.5 and RCP8.5. Source: <span class="citation">(<a href="References.html#ref-van_Vuuren_2011" role="doc-biblioref">Vuuren et al. 2011</a>)</span>
</p>
</div>
<div id="CHELSA21Century" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> High Res. Monthly Climate Time Series for 2006 - 2100</h3>
<p>The recently released high-resolution climate scenario datasets described by <span class="citation">(<a href="References.html#ref-Karger_2020" role="doc-biblioref">Karger et al. 2020</a>)</span> are utilized here to study climate impacts in river basins in the Central Asia region. The authors of the aforementioned paper present GCM output for monthly precipitation, mean minimum as well as maximum monthly temperatures that has been downscaled using the CHELSA algorithm.<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a> The data can be found here <a href="https://www.envidat.ch/#/metadata/chelsa_cmip5_ts" class="uri">https://www.envidat.ch/#/metadata/chelsa_cmip5_ts</a>.</p>
<p>We download data from 3 out of the 4 available downscaled GCM runs for further analysis and processing. These are outputs from the Coupled Model Intercomparison Project phase 5 (<a href="https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip5">CMIP5</a>) and are gridded monthly time series from the years 2006 through 2100 with a spatial resolution of 0.049 degrees (see again <span class="citation">(<a href="References.html#ref-Karger_2020" role="doc-biblioref">Karger et al. 2020</a>)</span> for all the details). The three models from which data were taken are: CMCC-CM run by the Centro Euro-Mediterraneo per I Cambiamenti Climatici (CMCC); MIROC5 run by the University of Tokyo; and ACCESS1-3 run by the Commonwealth Scientific and Industrial Research Organization (CSIRO) and Bureau of Meteorology (BOM), Australia <span class="citation">(<a href="References.html#ref-Karger_2020" role="doc-biblioref">Karger et al. 2020</a>)</span>.</p>
<p>First, the data is downloaded and stored locally for RCP 4.5 and RCP 8.5. Then, as in the case of the original CHELSA data (see Section <a href="Data-ClimateReanalysisData.html#ERA5::BiasCorrectionCHELSA">3.3.2.3</a>, the monthly gridded precipitation time series are bias corrected using the monthly correction factors as report by <span class="citation">(<a href="References.html#ref-beck2020c" role="doc-biblioref">Beck et al. 2020d</a>)</span> and finally, mean monthly temperature fields are generated from the minimum and maximum monthly temperatures. The resulting data available for the Central Asia domain are available for download via this <a href="https://www.dropbox.com/sh/xs870upjjvg9ovv/AABkniqG4f6XFzDkwZqhurcta?dl=0">link</a><a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a>.</p>
<p>As in the case of the ERA5 data, these GCM data need to be made available for all the elevation bands. By providing a proper shapefile that contains sub-basin specific elevation bands of a catchment, the function <code>riversCentralAsia::downscale_ClimPred_monthly_BasinElBands()</code> can be used to compute these data. The function processes the climate projection raster bricks with precipitation_flux and air_temperature (tasmin, tasmean and tasmax) and computes elevation band statistics. The next code block provides sample code on how to use <code>riversCentralAsia::downscale_ClimPred_monthly_BasinElBands()</code>.</p>
<p>Please be aware that if you want to try this locally on your computer, it is required that you download the entire high resolution climate scenarios for the Central Asia on your local machine. The data are available under this <a href="https://www.dropbox.com/sh/xs870upjjvg9ovv/AABkniqG4f6XFzDkwZqhurcta?dl=0">link</a>. The whole process is shown here using a shapefile of the Gunt river basin that explicitly includes Lake Yashikul in the upstream of the basin. In lieu of this example, your own catchment subbasin file can easily be loaded and provided.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="data-on-climate-projections.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data</span></span>
<span id="cb52-2"><a href="data-on-climate-projections.html#cb52-2" aria-hidden="true" tabindex="-1"></a>climScen_Path <span class="ot">&lt;-</span> <span class="st">&#39;../HydrologicalModeling_CentralAsia_Data/CentralAsiaDomain/PROJECTIONS/&#39;</span> <span class="co"># This Path would need to be adjusted for in case the directory with the climate projections is stored elsewhere.</span></span>
<span id="cb52-3"><a href="data-on-climate-projections.html#cb52-3" aria-hidden="true" tabindex="-1"></a>rcp <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;rcp45&#39;</span>,<span class="st">&#39;rcp85&#39;</span>)</span>
<span id="cb52-4"><a href="data-on-climate-projections.html#cb52-4" aria-hidden="true" tabindex="-1"></a>cModelList <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;ACCESS1-3&#39;</span>,<span class="st">&#39;CMCC-CM&#39;</span>,<span class="st">&#39;MIROC5&#39;</span>)</span>
<span id="cb52-5"><a href="data-on-climate-projections.html#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Catchment Shapefile</span></span>
<span id="cb52-6"><a href="data-on-climate-projections.html#cb52-6" aria-hidden="true" tabindex="-1"></a>elBands_shp <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&#39;./data/AmuDarya/GuntYashikul/GeospatialData/subbasins_Z.shp&#39;</span>)</span>
<span id="cb52-7"><a href="data-on-climate-projections.html#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure Projection is latlon</span></span>
<span id="cb52-8"><a href="data-on-climate-projections.html#cb52-8" aria-hidden="true" tabindex="-1"></a>elBands_shp_latlon <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_transform</span>(elBands_shp,<span class="at">crs =</span> sf<span class="sc">::</span><span class="fu">st_crs</span>(<span class="dv">4326</span>))</span>
<span id="cb52-9"><a href="data-on-climate-projections.html#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Unused catchments in RSMinerve? Preprocess Shapefile: This is specific for the Gunt-Yashikul model and can be removed if not required or change accordingly.</span></span>
<span id="cb52-10"><a href="data-on-climate-projections.html#cb52-10" aria-hidden="true" tabindex="-1"></a>elBands_shp_latlon <span class="ot">&lt;-</span> elBands_shp_latlon <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">slice</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">:-</span><span class="dv">3</span>)</span>
<span id="cb52-11"><a href="data-on-climate-projections.html#cb52-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-12"><a href="data-on-climate-projections.html#cb52-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Fancy trick to generate an empty dataframe with column names from a vector of characters.</span></span>
<span id="cb52-13"><a href="data-on-climate-projections.html#cb52-13" aria-hidden="true" tabindex="-1"></a>namesElBands <span class="ot">&lt;-</span> elBands_shp_latlon<span class="sc">$</span>name</span>
<span id="cb52-14"><a href="data-on-climate-projections.html#cb52-14" aria-hidden="true" tabindex="-1"></a>dataElBands_df <span class="ot">&lt;-</span> namesElBands <span class="sc">%&gt;%</span> purrr<span class="sc">::</span><span class="fu">map_dfc</span>(setNames, <span class="at">object =</span> base<span class="sc">::</span><span class="fu">list</span>(base<span class="sc">::</span><span class="fu">logical</span>())) </span>
<span id="cb52-15"><a href="data-on-climate-projections.html#cb52-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-16"><a href="data-on-climate-projections.html#cb52-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Start and end years of climate projections</span></span>
<span id="cb52-17"><a href="data-on-climate-projections.html#cb52-17" aria-hidden="true" tabindex="-1"></a>startY <span class="ot">&lt;-</span> <span class="dv">2006</span></span>
<span id="cb52-18"><a href="data-on-climate-projections.html#cb52-18" aria-hidden="true" tabindex="-1"></a>endY <span class="ot">&lt;-</span> <span class="dv">2100</span></span>
<span id="cb52-19"><a href="data-on-climate-projections.html#cb52-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-20"><a href="data-on-climate-projections.html#cb52-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Search pattern for file list</span></span>
<span id="cb52-21"><a href="data-on-climate-projections.html#cb52-21" aria-hidden="true" tabindex="-1"></a>fileListSearchPattern <span class="ot">&lt;-</span> <span class="st">&quot;2006-2100&quot;</span></span>
<span id="cb52-22"><a href="data-on-climate-projections.html#cb52-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-23"><a href="data-on-climate-projections.html#cb52-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate downscaled climate scenario files and store files in corresponding directory</span></span>
<span id="cb52-24"><a href="data-on-climate-projections.html#cb52-24" aria-hidden="true" tabindex="-1"></a><span class="co"># RCP45</span></span>
<span id="cb52-25"><a href="data-on-climate-projections.html#cb52-25" aria-hidden="true" tabindex="-1"></a>pathN <span class="ot">&lt;-</span> <span class="fu">paste0</span>(climScen_Path,<span class="st">&#39;rcp45&#39;</span>,<span class="st">&#39;/&#39;</span>,<span class="st">&#39;ACCESS1-3&#39;</span>,<span class="st">&#39;/&#39;</span>)</span>
<span id="cb52-26"><a href="data-on-climate-projections.html#cb52-26" aria-hidden="true" tabindex="-1"></a>downscaled_ClimPred_rcp45_ACCESS1_3 <span class="ot">&lt;-</span><span class="fu">downscale_ClimPred_monthly_BasinElBands</span>(pathN,fileListSearchPattern,</span>
<span id="cb52-27"><a href="data-on-climate-projections.html#cb52-27" aria-hidden="true" tabindex="-1"></a>                                                                              startY,endY,elBands_shp_latlon)</span>
<span id="cb52-28"><a href="data-on-climate-projections.html#cb52-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-29"><a href="data-on-climate-projections.html#cb52-29" aria-hidden="true" tabindex="-1"></a>pathN <span class="ot">&lt;-</span> <span class="fu">paste0</span>(climScen_Path,<span class="st">&#39;rcp45&#39;</span>,<span class="st">&#39;/&#39;</span>,<span class="st">&#39;CMCC-CM&#39;</span>,<span class="st">&#39;/&#39;</span>)</span>
<span id="cb52-30"><a href="data-on-climate-projections.html#cb52-30" aria-hidden="true" tabindex="-1"></a>downscaled_ClimPred_rcp45_CMCC_CM <span class="ot">&lt;-</span> <span class="fu">downscale_ClimPred_monthly_BasinElBands</span>(pathN,fileListSearchPattern,</span>
<span id="cb52-31"><a href="data-on-climate-projections.html#cb52-31" aria-hidden="true" tabindex="-1"></a>                                                                              startY,endY,elBands_shp_latlon)</span>
<span id="cb52-32"><a href="data-on-climate-projections.html#cb52-32" aria-hidden="true" tabindex="-1"></a>pathN <span class="ot">&lt;-</span> <span class="fu">paste0</span>(climScen_Path,<span class="st">&#39;rcp45&#39;</span>,<span class="st">&#39;/&#39;</span>,<span class="st">&#39;MIROC5&#39;</span>,<span class="st">&#39;/&#39;</span>)</span>
<span id="cb52-33"><a href="data-on-climate-projections.html#cb52-33" aria-hidden="true" tabindex="-1"></a>downscaled_ClimPred_rcp45_MIROC5 <span class="ot">&lt;-</span> <span class="fu">downscale_ClimPred_monthly_BasinElBands</span>(pathN,fileListSearchPattern,</span>
<span id="cb52-34"><a href="data-on-climate-projections.html#cb52-34" aria-hidden="true" tabindex="-1"></a>                                                                              startY,endY,elBands_shp_latlon)</span>
<span id="cb52-35"><a href="data-on-climate-projections.html#cb52-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-36"><a href="data-on-climate-projections.html#cb52-36" aria-hidden="true" tabindex="-1"></a><span class="co"># RCP85</span></span>
<span id="cb52-37"><a href="data-on-climate-projections.html#cb52-37" aria-hidden="true" tabindex="-1"></a>pathN <span class="ot">&lt;-</span> <span class="fu">paste0</span>(climScen_Path,<span class="st">&#39;rcp85&#39;</span>,<span class="st">&#39;/&#39;</span>,<span class="st">&#39;ACCESS1-3&#39;</span>,<span class="st">&#39;/&#39;</span>)</span>
<span id="cb52-38"><a href="data-on-climate-projections.html#cb52-38" aria-hidden="true" tabindex="-1"></a>downscaled_ClimPred_rcp85_ACCESS1_3 <span class="ot">&lt;-</span><span class="fu">downscale_ClimPred_monthly_BasinElBands</span>(pathN,fileListSearchPattern,</span>
<span id="cb52-39"><a href="data-on-climate-projections.html#cb52-39" aria-hidden="true" tabindex="-1"></a>                                                                              startY,endY,elBands_shp_latlon)</span>
<span id="cb52-40"><a href="data-on-climate-projections.html#cb52-40" aria-hidden="true" tabindex="-1"></a>pathN <span class="ot">&lt;-</span> <span class="fu">paste0</span>(climScen_Path,<span class="st">&#39;rcp85&#39;</span>,<span class="st">&#39;/&#39;</span>,<span class="st">&#39;CMCC-CM&#39;</span>,<span class="st">&#39;/&#39;</span>)</span>
<span id="cb52-41"><a href="data-on-climate-projections.html#cb52-41" aria-hidden="true" tabindex="-1"></a>downscaled_ClimPred_rcp85_CMCC_CM <span class="ot">&lt;-</span> <span class="fu">downscale_ClimPred_monthly_BasinElBands</span>(pathN,fileListSearchPattern,</span>
<span id="cb52-42"><a href="data-on-climate-projections.html#cb52-42" aria-hidden="true" tabindex="-1"></a>                                                                              startY,endY,elBands_shp_latlon)</span>
<span id="cb52-43"><a href="data-on-climate-projections.html#cb52-43" aria-hidden="true" tabindex="-1"></a>pathN <span class="ot">&lt;-</span> <span class="fu">paste0</span>(climScen_Path,<span class="st">&#39;rcp85&#39;</span>,<span class="st">&#39;/&#39;</span>,<span class="st">&#39;MIROC5&#39;</span>,<span class="st">&#39;/&#39;</span>)</span>
<span id="cb52-44"><a href="data-on-climate-projections.html#cb52-44" aria-hidden="true" tabindex="-1"></a>downscaled_ClimPred_rcp85_MIROC5 <span class="ot">&lt;-</span> <span class="fu">downscale_ClimPred_monthly_BasinElBands</span>(pathN,fileListSearchPattern,</span>
<span id="cb52-45"><a href="data-on-climate-projections.html#cb52-45" aria-hidden="true" tabindex="-1"></a>                                                                              startY,endY,elBands_shp_latlon)</span>
<span id="cb52-46"><a href="data-on-climate-projections.html#cb52-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-47"><a href="data-on-climate-projections.html#cb52-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Store files if required in the corresponding catchment-specific folder. For the example presented here, this is in the following directory.</span></span>
<span id="cb52-48"><a href="data-on-climate-projections.html#cb52-48" aria-hidden="true" tabindex="-1"></a><span class="co"># basin_climScen_Path &lt;- &#39;./data/AmuDarya/GuntYashikul/ClimateProjections/&#39;</span></span>
<span id="cb52-49"><a href="data-on-climate-projections.html#cb52-49" aria-hidden="true" tabindex="-1"></a><span class="co">#  </span></span>
<span id="cb52-50"><a href="data-on-climate-projections.html#cb52-50" aria-hidden="true" tabindex="-1"></a><span class="co"># climScen_fileList &lt;- c(&#39;downscaled_ClimPred_rcp45_ACCESS1_3&#39;, &#39;downscaled_ClimPred_rcp45_CMCC_CM&#39;,</span></span>
<span id="cb52-51"><a href="data-on-climate-projections.html#cb52-51" aria-hidden="true" tabindex="-1"></a><span class="co">#                &#39;downscaled_ClimPred_rcp45_MIROC5&#39;,&#39;downscaled_ClimPred_rcp85_ACCESS1_3&#39;,</span></span>
<span id="cb52-52"><a href="data-on-climate-projections.html#cb52-52" aria-hidden="true" tabindex="-1"></a><span class="co">#                &#39;downscaled_ClimPred_rcp85_CMCC_CM&#39;,&#39;downscaled_ClimPred_rcp85_MIROC5&#39;)</span></span>
<span id="cb52-53"><a href="data-on-climate-projections.html#cb52-53" aria-hidden="true" tabindex="-1"></a><span class="co">#  </span></span>
<span id="cb52-54"><a href="data-on-climate-projections.html#cb52-54" aria-hidden="true" tabindex="-1"></a><span class="co"># save(climScen_fileList,list = climScen_fileList,file = paste0(basin_climScen_Path,&#39;climScen_monthly&#39;,&#39;.rda&#39;))</span></span></code></pre></div>
<p>It is important to mention that precipitation is stored in units of kg/m<sup>2</sup>/s in these climate projection data. How do we arrive at mm/month in order to make these data compatible with the ERA5 data? To answer this question, let us make a little thought experiment. What happens when you pour 1 kg of water on a 1 m<sup>2</sup> big patch? 1 kg corresponds to 1 liter that corresponds to 10<sup>-3</sup> m<sup>3</sup>. So, very simply, this amount of water poured on such a patch generates a water height of exactly 1 mm. Using this equivalence, we can rewrite the unit kg/m<sup>2</sup>/s to mm/s. Finally, in order to arrive at mm/day, for example, we just multiply the data by 60x60x24 = 86’400 which are the number of seconds in a day. Since the climate model output is in monthly time intervals, we need mm/month and hence would also need to multiply by the number of days in the corresponding month.</p>
<p>As discussed, these GCM data are high spatial resolution monthly future climate fields which we downscaled on the corresponding catchment shapefile with its subbasins and elevation bands. All good. But how do we arrive at climate fields that also have a high temporal resolution (hourly time resolution in this case) so that we can drive the RS MINERVE hydrological model with the required input data? The solution is shown in the following Section @ref(<a href="Data::WeatherGenerator" class="uri">Data::WeatherGenerator</a>) using a weather generator. A weather generator is a stochastic model that produces daily weather variables which can then be converted to hourly fields.</p>
</div>
<div id="Data::WeatherGenerator" class="section level3" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Using a Weather Generator to Simulate Daily Future Climate</h3>
<div id="background-and-input-file-generation" class="section level4" number="3.4.2.1">
<h4><span class="header-section-number">3.4.2.1</span> Background and Input File Generation</h4>
<p>Stochastic weather generators are probabilistic models that are used to simulate weather data at a specific site or region by analyzing historical weather data and then generating a time-series of weather variables with statistical properties identical to the historical data <span class="citation">(<a href="References.html#ref-BIRT20101252" role="doc-biblioref">Birt et al. 2010</a>)</span>. We demonstrate the use of RMAWGEN, a stochastic weather generator available for the <code>R</code> environment. Further information on RMAWGEN can be found here <a href="https://github.com/ecor/RMAWGEN" class="uri">https://github.com/ecor/RMAWGEN</a> and under the links provided via the package information on GitHub.</p>
<p>While the weather generator is relatively poorly documented, a useful albeit very technical presentation of the tool is available <a href="https://docs.google.com/file/d/0B66otCUk3Bv6V3RPbm1mUG4zVHc/edit">here</a>. Furthermore, the functions are documented well in the latest development version of the package. The package can be installed in the following way directly from GitHub:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="data-on-climate-projections.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install GitHub version</span></span>
<span id="cb53-2"><a href="data-on-climate-projections.html#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(devtools)</span>
<span id="cb53-3"><a href="data-on-climate-projections.html#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install_github</span>(<span class="st">&quot;ecor/RMAWGEN&quot;</span>)</span>
<span id="cb53-4"><a href="data-on-climate-projections.html#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RMAWGEN)</span></code></pre></div>
<p>RMAWGEN allows for the generation of daily temperature and precipitation scenarios that are conditioned on monthly climate scenario totals as given by the GCM model outputs. This is the key idea. Using again an example of the Gunt-Yashikul river basin, the following code block shows how to use the function <code>prepare_RMAWGEN_input_data()</code> for the preparation of the relevant RMAWGEN input data files so that the weather generator can be run.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="data-on-climate-projections.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and process RS MINERVE csv database file</span></span>
<span id="cb54-2"><a href="data-on-climate-projections.html#cb54-2" aria-hidden="true" tabindex="-1"></a>filePath <span class="ot">&lt;-</span> <span class="st">&#39;./data/AmuDarya/GuntYashikul/RSMinerve/&#39;</span></span>
<span id="cb54-3"><a href="data-on-climate-projections.html#cb54-3" aria-hidden="true" tabindex="-1"></a>fileName <span class="ot">&lt;-</span> <span class="st">&#39;Gunt_Yashikul_1981_2013_db.csv&#39;</span></span>
<span id="cb54-4"><a href="data-on-climate-projections.html#cb54-4" aria-hidden="true" tabindex="-1"></a>era5_gunt_yashikul_1 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="fu">paste0</span>(filePath,fileName),<span class="at">sep=</span><span class="st">&#39;,&#39;</span>) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb54-5"><a href="data-on-climate-projections.html#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="data-on-climate-projections.html#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Deleting unused catchments in the tibble. These catchments are not modeled later in RS MINERVE, so we can safely delete them here. Note that this operation is specific to the Gunt-Yashikul model and does not generalize to other catchments.</span></span>
<span id="cb54-7"><a href="data-on-climate-projections.html#cb54-7" aria-hidden="true" tabindex="-1"></a>idx2del <span class="ot">&lt;-</span> </span>
<span id="cb54-8"><a href="data-on-climate-projections.html#cb54-8" aria-hidden="true" tabindex="-1"></a>  (era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_1&#39;</span>)<span class="sc">|</span></span>
<span id="cb54-9"><a href="data-on-climate-projections.html#cb54-9" aria-hidden="true" tabindex="-1"></a>  (era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_2&#39;</span>)<span class="sc">|</span></span>
<span id="cb54-10"><a href="data-on-climate-projections.html#cb54-10" aria-hidden="true" tabindex="-1"></a>  (era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_3&#39;</span>)</span>
<span id="cb54-11"><a href="data-on-climate-projections.html#cb54-11" aria-hidden="true" tabindex="-1"></a>era5_gunt_yashikul <span class="ot">&lt;-</span> era5_gunt_yashikul <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">which</span>(<span class="sc">!</span>idx2del))</span>
<span id="cb54-12"><a href="data-on-climate-projections.html#cb54-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-13"><a href="data-on-climate-projections.html#cb54-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the input files for the stochastic weather generator.</span></span>
<span id="cb54-14"><a href="data-on-climate-projections.html#cb54-14" aria-hidden="true" tabindex="-1"></a>station_data <span class="ot">&lt;-</span> <span class="fu">prepare_RMAWGEN_input_data</span>(era5_gunt_yashikul)</span>
<span id="cb54-15"><a href="data-on-climate-projections.html#cb54-15" aria-hidden="true" tabindex="-1"></a><span class="co"># In case variables in station_data list should not be made available directly on the workspace, on can comment out the following line of code.</span></span>
<span id="cb54-16"><a href="data-on-climate-projections.html#cb54-16" aria-hidden="true" tabindex="-1"></a>station_data <span class="sc">%&gt;%</span> <span class="fu">list2env</span>(.,<span class="at">envir =</span> .GlobalEnv) <span class="co"># Send list variables to global environment.</span></span></code></pre></div>
<p>The function returns a list <code>rmawgen_input_files</code> with all key information that can be unlisted using <code>rmawgen_input_files %&gt;% list2env(.,envir = .GlobalEnv)</code>. Data returned are:</p>
<ul>
<li><p>STATION_NAMES: Character vector of station names (effectively, these are just the subbasin names extracted from the RS MINERVE input file).</p></li>
<li><p>ELEVATION: Mean elevation of the stations</p></li>
<li><p>STATION_LATLON: Matrix with station names, latitude and longitude</p></li>
<li><p>LOCATION: Same as the station name, used above.</p></li>
<li><p>PRECIPITATION: Tibble containing daily precipitation for each station</p></li>
<li><p>TEMPERATURE_MIN: Minimum daily temperature (calculated from the ERA5 hourly data stored in the RS MINERVE csv file)</p></li>
<li><p>TEMPERATURE_MAX: Maximum daily temperature (ditto)</p></li>
</ul>
<p>A weather generator is a type of model that uses input data to simulate output variables, i.e. daily precipitation and minimum as well as maximum temperatures. Exactly like for example a hydrological runoff model, the stochastic weather generator model depends on input parameters. Different input parameter configuration lead to different model performance / outcomes. How are these parameters calibrated and how is such a model validated when we do not have calibration and validation sets available for the future periods for which climate impacts need to be studied?</p>
<p>The way to do this is to calibrate and validate the stochastic weather generator with reanalysis ERA5 data for each elevation band in the catchment of interest. In other words, we assume that each elevation band contains a representative meteorological station for which we have the ERA5 data available which is used to calibrate and validate daily weather generator models. In this context, the terms <em>elevation bands</em> and <em>meteorological stations</em> are used interchangeably.</p>
<p>The key question to be answered then is whether or not the model is able to reproduce the statistical characteristics of the ERA5 dataset for each elevation band/station. If yes, we can safely assume that the weather generator can in a more or less realistic manner generate stochastic future daily climate fields that are conditioned on local conditions and on the monthly minimum and maximum temperature and precipitation fields from the climate projections.</p>
<p>A typical parameter set of RMAWGEN for testing different models with different parameters can be specified in the following way.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="data-on-climate-projections.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Housekeeping</span></span>
<span id="cb55-2"><a href="data-on-climate-projections.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123456</span>) <span class="co"># Random generator seed is set to make results reproducible.</span></span>
<span id="cb55-3"><a href="data-on-climate-projections.html#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="data-on-climate-projections.html#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Monthly climate is calculated if it is set to NULL.</span></span>
<span id="cb55-5"><a href="data-on-climate-projections.html#cb55-5" aria-hidden="true" tabindex="-1"></a>PREC_CLIMATE <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb55-6"><a href="data-on-climate-projections.html#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="data-on-climate-projections.html#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calibration Period</span></span>
<span id="cb55-8"><a href="data-on-climate-projections.html#cb55-8" aria-hidden="true" tabindex="-1"></a>year_min <span class="ot">&lt;-</span> <span class="dv">1981</span></span>
<span id="cb55-9"><a href="data-on-climate-projections.html#cb55-9" aria-hidden="true" tabindex="-1"></a>year_max <span class="ot">&lt;-</span> <span class="dv">2013</span></span>
<span id="cb55-10"><a href="data-on-climate-projections.html#cb55-10" aria-hidden="true" tabindex="-1"></a>origin <span class="ot">&lt;-</span> <span class="st">&quot;1981-1-1&quot;</span> <span class="co"># This is the starting date for which we have data available.</span></span>
<span id="cb55-11"><a href="data-on-climate-projections.html#cb55-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-12"><a href="data-on-climate-projections.html#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="co"># n GPCA iterations for variable and VAR residuals</span></span>
<span id="cb55-13"><a href="data-on-climate-projections.html#cb55-13" aria-hidden="true" tabindex="-1"></a>n_GPCA_iter <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb55-14"><a href="data-on-climate-projections.html#cb55-14" aria-hidden="true" tabindex="-1"></a>n_GPCA_iteration_residuals <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb55-15"><a href="data-on-climate-projections.html#cb55-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-16"><a href="data-on-climate-projections.html#cb55-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Autoregression orders (p) and exogenous vars</span></span>
<span id="cb55-17"><a href="data-on-climate-projections.html#cb55-17" aria-hidden="true" tabindex="-1"></a>p_test <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb55-18"><a href="data-on-climate-projections.html#cb55-18" aria-hidden="true" tabindex="-1"></a>p_prec <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb55-19"><a href="data-on-climate-projections.html#cb55-19" aria-hidden="true" tabindex="-1"></a>exogen <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb55-20"><a href="data-on-climate-projections.html#cb55-20" aria-hidden="true" tabindex="-1"></a>exogen_sim <span class="ot">&lt;-</span> exogen</span>
<span id="cb55-21"><a href="data-on-climate-projections.html#cb55-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-22"><a href="data-on-climate-projections.html#cb55-22" aria-hidden="true" tabindex="-1"></a><span class="co"># number of weather realizations</span></span>
<span id="cb55-23"><a href="data-on-climate-projections.html#cb55-23" aria-hidden="true" tabindex="-1"></a>nscenario <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb55-24"><a href="data-on-climate-projections.html#cb55-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-25"><a href="data-on-climate-projections.html#cb55-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulation period</span></span>
<span id="cb55-26"><a href="data-on-climate-projections.html#cb55-26" aria-hidden="true" tabindex="-1"></a>year_min_sim <span class="ot">&lt;-</span>  year_min <span class="co"># we are not yet simulating future climate but use the available data for model assessment, hence year_min_sim = year_min</span></span>
<span id="cb55-27"><a href="data-on-climate-projections.html#cb55-27" aria-hidden="true" tabindex="-1"></a>year_max_sim <span class="ot">&lt;-</span>  year_max <span class="co"># we are not yet simulating future climate but use the available data for model assessment, hence year_max_sim = year_max</span></span>
<span id="cb55-28"><a href="data-on-climate-projections.html#cb55-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-29"><a href="data-on-climate-projections.html#cb55-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Minimum Precipitation value below which no precip is considered</span></span>
<span id="cb55-30"><a href="data-on-climate-projections.html#cb55-30" aria-hidden="true" tabindex="-1"></a>valmin <span class="ot">&lt;-</span> <span class="fl">1.0</span></span></code></pre></div>
<p>The different parameter configurations will be used to run different stochastic weather generator models. In a validation step, the best model will be chosen as explained in the next Section <a href="data-on-climate-projections.html#StochasticWGEN::ModelCalibrationValidation">3.4.2.2</a>.</p>
</div>
<div id="StochasticWGEN::ModelCalibrationValidation" class="section level4" number="3.4.2.2">
<h4><span class="header-section-number">3.4.2.2</span> Model Calibration &amp; Validation for Model Selection</h4>
<p>Different parameter combinations can be tested be setting up different models. The performance of the individual models is then assessed as a function of these configurations. We show the process by specifying 4 weather generator models, i.e. <code>model1</code> through <code>model4</code> and then generate the model output which is finally compared with the observed ERA5 data over the 1981 - 2013 period. The model that reproduces the <em>observed</em> ERA5 data in the best possible manner is then selected as the final weather generator model. The process is demonstrated here for the Gunt-Yahsikul river basin<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a>.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="data-on-climate-projections.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># P03GPCA_prec</span></span>
<span id="cb56-2"><a href="data-on-climate-projections.html#cb56-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">ComprehensivePrecipitationGenerator</span>(</span>
<span id="cb56-3"><a href="data-on-climate-projections.html#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">station =</span> STATION_NAMES,</span>
<span id="cb56-4"><a href="data-on-climate-projections.html#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">prec_all =</span> PRECIPITATION,</span>
<span id="cb56-5"><a href="data-on-climate-projections.html#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_min =</span> year_min,</span>
<span id="cb56-6"><a href="data-on-climate-projections.html#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_max =</span> year_max,</span>
<span id="cb56-7"><a href="data-on-climate-projections.html#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> p_prec,</span>
<span id="cb56-8"><a href="data-on-climate-projections.html#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_GPCA_iteration =</span> n_GPCA_iter,</span>
<span id="cb56-9"><a href="data-on-climate-projections.html#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_GPCA_iteration_residuals =</span> n_GPCA_iteration_residuals, </span>
<span id="cb56-10"><a href="data-on-climate-projections.html#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">exogen =</span> exogen,</span>
<span id="cb56-11"><a href="data-on-climate-projections.html#cb56-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">exogen_sim =</span> exogen_sim, </span>
<span id="cb56-12"><a href="data-on-climate-projections.html#cb56-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample =</span> <span class="st">&quot;monthly&quot;</span>,</span>
<span id="cb56-13"><a href="data-on-climate-projections.html#cb56-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_climate_prec =</span> PREC_CLIMATE,</span>
<span id="cb56-14"><a href="data-on-climate-projections.html#cb56-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">no_spline =</span> <span class="cn">FALSE</span>,</span>
<span id="cb56-15"><a href="data-on-climate-projections.html#cb56-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_max_sim =</span> year_max_sim,</span>
<span id="cb56-16"><a href="data-on-climate-projections.html#cb56-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_min_sim =</span> year_min_sim</span>
<span id="cb56-17"><a href="data-on-climate-projections.html#cb56-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb56-18"><a href="data-on-climate-projections.html#cb56-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-19"><a href="data-on-climate-projections.html#cb56-19" aria-hidden="true" tabindex="-1"></a><span class="co"># P01GPCA</span></span>
<span id="cb56-20"><a href="data-on-climate-projections.html#cb56-20" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">ComprehensivePrecipitationGenerator</span>(</span>
<span id="cb56-21"><a href="data-on-climate-projections.html#cb56-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">station =</span> STATION_NAMES,</span>
<span id="cb56-22"><a href="data-on-climate-projections.html#cb56-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">prec_all =</span> PRECIPITATION,</span>
<span id="cb56-23"><a href="data-on-climate-projections.html#cb56-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_min =</span> year_min,</span>
<span id="cb56-24"><a href="data-on-climate-projections.html#cb56-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_max =</span> year_max,</span>
<span id="cb56-25"><a href="data-on-climate-projections.html#cb56-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> p_test,</span>
<span id="cb56-26"><a href="data-on-climate-projections.html#cb56-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_GPCA_iteration =</span> n_GPCA_iter,</span>
<span id="cb56-27"><a href="data-on-climate-projections.html#cb56-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_GPCA_iteration_residuals =</span> n_GPCA_iteration_residuals, </span>
<span id="cb56-28"><a href="data-on-climate-projections.html#cb56-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">exogen =</span> exogen,</span>
<span id="cb56-29"><a href="data-on-climate-projections.html#cb56-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">exogen_sim =</span> exogen_sim, </span>
<span id="cb56-30"><a href="data-on-climate-projections.html#cb56-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample =</span> <span class="st">&quot;monthly&quot;</span>,</span>
<span id="cb56-31"><a href="data-on-climate-projections.html#cb56-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_climate_prec =</span> PREC_CLIMATE,</span>
<span id="cb56-32"><a href="data-on-climate-projections.html#cb56-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">no_spline =</span> <span class="cn">FALSE</span>,</span>
<span id="cb56-33"><a href="data-on-climate-projections.html#cb56-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_max_sim =</span> year_max_sim,</span>
<span id="cb56-34"><a href="data-on-climate-projections.html#cb56-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_min_sim =</span> year_min_sim</span>
<span id="cb56-35"><a href="data-on-climate-projections.html#cb56-35" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb56-36"><a href="data-on-climate-projections.html#cb56-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-37"><a href="data-on-climate-projections.html#cb56-37" aria-hidden="true" tabindex="-1"></a><span class="co"># P03</span></span>
<span id="cb56-38"><a href="data-on-climate-projections.html#cb56-38" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">ComprehensivePrecipitationGenerator</span>(</span>
<span id="cb56-39"><a href="data-on-climate-projections.html#cb56-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">station =</span> STATION_NAMES,</span>
<span id="cb56-40"><a href="data-on-climate-projections.html#cb56-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">prec_all =</span> PRECIPITATION,</span>
<span id="cb56-41"><a href="data-on-climate-projections.html#cb56-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_min =</span> year_min,</span>
<span id="cb56-42"><a href="data-on-climate-projections.html#cb56-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_max =</span> year_max,</span>
<span id="cb56-43"><a href="data-on-climate-projections.html#cb56-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> p_prec,</span>
<span id="cb56-44"><a href="data-on-climate-projections.html#cb56-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_GPCA_iteration =</span> <span class="dv">0</span>,</span>
<span id="cb56-45"><a href="data-on-climate-projections.html#cb56-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_GPCA_iteration_residuals =</span> <span class="dv">0</span>, </span>
<span id="cb56-46"><a href="data-on-climate-projections.html#cb56-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">exogen =</span> exogen,</span>
<span id="cb56-47"><a href="data-on-climate-projections.html#cb56-47" aria-hidden="true" tabindex="-1"></a>  <span class="at">exogen_sim =</span> exogen_sim, </span>
<span id="cb56-48"><a href="data-on-climate-projections.html#cb56-48" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample =</span> <span class="st">&quot;monthly&quot;</span>,</span>
<span id="cb56-49"><a href="data-on-climate-projections.html#cb56-49" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_climate_prec =</span> PREC_CLIMATE,</span>
<span id="cb56-50"><a href="data-on-climate-projections.html#cb56-50" aria-hidden="true" tabindex="-1"></a>  <span class="at">no_spline =</span> <span class="cn">FALSE</span>,</span>
<span id="cb56-51"><a href="data-on-climate-projections.html#cb56-51" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_max_sim =</span> year_max_sim,</span>
<span id="cb56-52"><a href="data-on-climate-projections.html#cb56-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_min_sim =</span> year_min_sim</span>
<span id="cb56-53"><a href="data-on-climate-projections.html#cb56-53" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb56-54"><a href="data-on-climate-projections.html#cb56-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-55"><a href="data-on-climate-projections.html#cb56-55" aria-hidden="true" tabindex="-1"></a><span class="co"># P01</span></span>
<span id="cb56-56"><a href="data-on-climate-projections.html#cb56-56" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">ComprehensivePrecipitationGenerator</span>(</span>
<span id="cb56-57"><a href="data-on-climate-projections.html#cb56-57" aria-hidden="true" tabindex="-1"></a>  <span class="at">station =</span> STATION_NAMES,</span>
<span id="cb56-58"><a href="data-on-climate-projections.html#cb56-58" aria-hidden="true" tabindex="-1"></a>  <span class="at">prec_all =</span> PRECIPITATION,</span>
<span id="cb56-59"><a href="data-on-climate-projections.html#cb56-59" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_min =</span> year_min,</span>
<span id="cb56-60"><a href="data-on-climate-projections.html#cb56-60" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_max =</span> year_max,</span>
<span id="cb56-61"><a href="data-on-climate-projections.html#cb56-61" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> p_test,</span>
<span id="cb56-62"><a href="data-on-climate-projections.html#cb56-62" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_GPCA_iteration =</span> <span class="dv">0</span>,</span>
<span id="cb56-63"><a href="data-on-climate-projections.html#cb56-63" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_GPCA_iteration_residuals =</span> <span class="dv">0</span>, </span>
<span id="cb56-64"><a href="data-on-climate-projections.html#cb56-64" aria-hidden="true" tabindex="-1"></a>  <span class="at">exogen =</span> exogen,</span>
<span id="cb56-65"><a href="data-on-climate-projections.html#cb56-65" aria-hidden="true" tabindex="-1"></a>  <span class="at">exogen_sim =</span> exogen_sim, </span>
<span id="cb56-66"><a href="data-on-climate-projections.html#cb56-66" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample =</span> <span class="st">&quot;monthly&quot;</span>,</span>
<span id="cb56-67"><a href="data-on-climate-projections.html#cb56-67" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_climate_prec =</span> PREC_CLIMATE,</span>
<span id="cb56-68"><a href="data-on-climate-projections.html#cb56-68" aria-hidden="true" tabindex="-1"></a>  <span class="at">no_spline =</span> <span class="cn">FALSE</span>,</span>
<span id="cb56-69"><a href="data-on-climate-projections.html#cb56-69" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_max_sim =</span> year_max_sim,</span>
<span id="cb56-70"><a href="data-on-climate-projections.html#cb56-70" aria-hidden="true" tabindex="-1"></a>  <span class="at">year_min_sim =</span> year_min_sim</span>
<span id="cb56-71"><a href="data-on-climate-projections.html#cb56-71" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>The performance of the 4 models can be assessed with statistical tests and graphically, with qq-plots and through the comparison of simulated versus observed monthly precipitation totals. Results are shown in the Figures below.</p>
<div class="figure"><span id="fig:rmawgenMonthlyTotals"></span>
<img src="_bookdown_files/FIG_DATA/RMAWGEN_Models_monthlyTotalsComparison.jpg" alt="The comparison of the 4 stochastic weather generator models in terms of their abilities to reproduce monthly precipitation totals is shown for one station (elevation band Alishur_2) in the Gunt river basin. Measured monthly totals (mes) are shown on the x-axis and simulated monthly totals (sim) on the y-axis. Results indicate that precipitation totals from the models 1 and 2 are overestimated. In comparison, results from the models 3 and 4 are more balanced and not biased." width="910" />
<p class="caption">
Figure 3.50: The comparison of the 4 stochastic weather generator models in terms of their abilities to reproduce monthly precipitation totals is shown for one station (elevation band Alishur_2) in the Gunt river basin. Measured monthly totals (mes) are shown on the x-axis and simulated monthly totals (sim) on the y-axis. Results indicate that precipitation totals from the models 1 and 2 are overestimated. In comparison, results from the models 3 and 4 are more balanced and not biased.
</p>
</div>
<div class="figure"><span id="fig:rmawgenQQPlot"></span>
<img src="_bookdown_files/FIG_DATA/RMAWGEN_Models_qqplot.jpg" alt="QQ-Plots of the four model results. If data plots along the diagonal line, it is an indication that the probability distribution of the simluated precipptation (y-axis) is the same as the probability distribution of the observed ERA5 precipitation (x-axis). QQ-plots of models 1 and 2 show a heavy bias whereas model 4 shows an overal satisfactory fit and thus performance. " width="1467" />
<p class="caption">
Figure 3.51: QQ-Plots of the four model results. If data plots along the diagonal line, it is an indication that the probability distribution of the simluated precipptation (y-axis) is the same as the probability distribution of the observed ERA5 precipitation (x-axis). QQ-plots of models 1 and 2 show a heavy bias whereas model 4 shows an overal satisfactory fit and thus performance.
</p>
</div>
<p>All four models pass the multivariate Portmanteau and Breusch-Godfrey (Lagrange Multiplier) tests, which verify the absence of time-autocorrelation of the VAR(p) residuals in the modeled precipitation time series (seriality test). Furthermore, all models pass the Jarque-Bera multivariate skewness and kurtosis test, which validate the multivariate Gaussian probability distribution of the VAR(p) residuals (normality test). See <span class="citation">(<a href="#ref-Pfaff_2008" role="doc-biblioref"><strong>Pfaff_2008?</strong></a>)</span> for more information.</p>
<p>Figure <a href="data-on-climate-projections.html#fig:rmawgenMonthlyTotals">3.50</a> and Figure <a href="data-on-climate-projections.html#fig:rmawgenQQPlot">3.51</a> show that the Model 4 provides an overall well-balanced performance. We will thus us this models to generate the future climate fields in the Gunt river basin.</p>
<p>Temperature is not independent of precipitation and vice versa. The two climate state variables and their changes are interlinked. In the warm season over continents, higher temperatures accompany lower precipitation amounts and vice versa. Hence, over land, strong negative correlations dominate, as dry conditions favor more sunshine and less evaporative cooling, while wet summers are cool (see e.g. IPCC Fourth Assessment Report: Climate Change 2007, Working Group I, The Physical Science Basis, Section 3.3.5, available <a href="https://archive.ipcc.ch/publications_and_data/ar4/wg1/en/ch3s3-3-5.html">here</a>). Simply put, on rainy cloudy days, there is less radiation for warming the earth surface and vice versa.</p>
<p>This coupling needs to be taken into account when simulating weather. Therefore, we use the <code>model4</code> configuration to first generate multi-site synthetic future precipitation time series. Second, we use precipitation as exogenous predictors in the temperature generation step (tasmin and tasmax). Like this, we can coupled temperature simulation to precipitation. If the results are satisfactory, we proceed with this stochastic weather model to produce future simulated weather runs that are conditioned on GCM output for the mid-21st (Period 1) and end of 21st century (Period 2).</p>
</div>
<div id="coupling-precipitation-realizations-with-temperature" class="section level4" number="3.4.2.3">
<h4><span class="header-section-number">3.4.2.3</span> Coupling Precipitation Realizations with Temperature</h4>
<p>For initiating and running the weather generator, the <code>riversCentralAsia::wgen_daily_PT()</code> function can be used. It is a wrapper function that minimizes code reuse and allows to easily run RMAWGEN for the baseline period and/or for the future target period of the climate scenario under consideration. The use of the function is demonstrated below for a subset of 2 out of the complete set of all 17 stations in the Gunt-Yashikul catchment.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="data-on-climate-projections.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Station Data</span></span>
<span id="cb57-2"><a href="data-on-climate-projections.html#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Load and process RS MINERVE csv database file</span></span>
<span id="cb57-3"><a href="data-on-climate-projections.html#cb57-3" aria-hidden="true" tabindex="-1"></a>filePath <span class="ot">&lt;-</span> <span class="st">&#39;./data/AmuDarya/GuntYashikul/RSMinerve/&#39;</span></span>
<span id="cb57-4"><a href="data-on-climate-projections.html#cb57-4" aria-hidden="true" tabindex="-1"></a>fileName <span class="ot">&lt;-</span> <span class="st">&#39;Gunt_Yashikul_1981_2013_db.csv&#39;</span></span>
<span id="cb57-5"><a href="data-on-climate-projections.html#cb57-5" aria-hidden="true" tabindex="-1"></a>era5_gunt_yashikul <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="fu">paste0</span>(filePath,fileName),<span class="at">sep=</span><span class="st">&#39;,&#39;</span>) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb57-6"><a href="data-on-climate-projections.html#cb57-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-7"><a href="data-on-climate-projections.html#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Delete unused catchments in the Gunt-Yashikul hydrological model (this is specific to the model and does not need to be carried out normally)</span></span>
<span id="cb57-8"><a href="data-on-climate-projections.html#cb57-8" aria-hidden="true" tabindex="-1"></a>idx2del <span class="ot">&lt;-</span> (era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_1&#39;</span>) <span class="sc">|</span> (era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_2&#39;</span>) <span class="sc">|</span> </span>
<span id="cb57-9"><a href="data-on-climate-projections.html#cb57-9" aria-hidden="true" tabindex="-1"></a>  (era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_3&#39;</span>)</span>
<span id="cb57-10"><a href="data-on-climate-projections.html#cb57-10" aria-hidden="true" tabindex="-1"></a>era5_gunt_yashikul <span class="ot">&lt;-</span> era5_gunt_yashikul <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">which</span>(<span class="sc">!</span>idx2del))</span>
<span id="cb57-11"><a href="data-on-climate-projections.html#cb57-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-12"><a href="data-on-climate-projections.html#cb57-12" aria-hidden="true" tabindex="-1"></a><span class="do">## Generate list containing all station data (this is an input to the wgen_daily_PT() function)</span></span>
<span id="cb57-13"><a href="data-on-climate-projections.html#cb57-13" aria-hidden="true" tabindex="-1"></a>station_data <span class="ot">&lt;-</span> <span class="fu">prepare_RMAWGEN_input_data</span>(era5_gunt_yashikul)</span>
<span id="cb57-14"><a href="data-on-climate-projections.html#cb57-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-15"><a href="data-on-climate-projections.html#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. RMAWGEN PARAMETERS</span></span>
<span id="cb57-16"><a href="data-on-climate-projections.html#cb57-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Note: all parameteres are stored in the param list</span></span>
<span id="cb57-17"><a href="data-on-climate-projections.html#cb57-17" aria-hidden="true" tabindex="-1"></a>param <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb57-18"><a href="data-on-climate-projections.html#cb57-18" aria-hidden="true" tabindex="-1"></a><span class="do">## Random generator seed</span></span>
<span id="cb57-19"><a href="data-on-climate-projections.html#cb57-19" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>seed <span class="ot">&lt;-</span> <span class="dv">123456</span></span>
<span id="cb57-20"><a href="data-on-climate-projections.html#cb57-20" aria-hidden="true" tabindex="-1"></a><span class="do">## Monthly climate is calculated if it is set to NULL</span></span>
<span id="cb57-21"><a href="data-on-climate-projections.html#cb57-21" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>PREC_CLIMATE <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb57-22"><a href="data-on-climate-projections.html#cb57-22" aria-hidden="true" tabindex="-1"></a><span class="do">## Calibration Period</span></span>
<span id="cb57-23"><a href="data-on-climate-projections.html#cb57-23" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_min <span class="ot">&lt;-</span> <span class="dv">1981</span></span>
<span id="cb57-24"><a href="data-on-climate-projections.html#cb57-24" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_max <span class="ot">&lt;-</span> <span class="dv">2013</span></span>
<span id="cb57-25"><a href="data-on-climate-projections.html#cb57-25" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>origin <span class="ot">&lt;-</span> <span class="st">&quot;1981-1-1&quot;</span></span>
<span id="cb57-26"><a href="data-on-climate-projections.html#cb57-26" aria-hidden="true" tabindex="-1"></a><span class="do">## n GPCA iterations for variable and VAR residuals</span></span>
<span id="cb57-27"><a href="data-on-climate-projections.html#cb57-27" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>n_GPCA_iter <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb57-28"><a href="data-on-climate-projections.html#cb57-28" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>n_GPCA_iteration_residuals <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb57-29"><a href="data-on-climate-projections.html#cb57-29" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>n_GPCA_iter_prec <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb57-30"><a href="data-on-climate-projections.html#cb57-30" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>n_GPCA_iteration_residuals_prec <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb57-31"><a href="data-on-climate-projections.html#cb57-31" aria-hidden="true" tabindex="-1"></a><span class="do">## Autoregressive order (p)</span></span>
<span id="cb57-32"><a href="data-on-climate-projections.html#cb57-32" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>p <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb57-33"><a href="data-on-climate-projections.html#cb57-33" aria-hidden="true" tabindex="-1"></a><span class="co"># number of weather realizations</span></span>
<span id="cb57-34"><a href="data-on-climate-projections.html#cb57-34" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>nscenario <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb57-35"><a href="data-on-climate-projections.html#cb57-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Multi-site stations</span></span>
<span id="cb57-36"><a href="data-on-climate-projections.html#cb57-36" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>station <span class="ot">&lt;-</span> station_data<span class="sc">$</span>STATION_NAMES</span>
<span id="cb57-37"><a href="data-on-climate-projections.html#cb57-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Minimum precipitation cutoff value, i.e. threshold value below which a no precipitation event is recorded [in mm/day]</span></span>
<span id="cb57-38"><a href="data-on-climate-projections.html#cb57-38" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>valmin <span class="ot">&lt;-</span> <span class="fl">1.0</span></span>
<span id="cb57-39"><a href="data-on-climate-projections.html#cb57-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-40"><a href="data-on-climate-projections.html#cb57-40" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Compute stochastic weather for a subset of 2 sample stations for the calibration period 1981 - 2013</span></span>
<span id="cb57-41"><a href="data-on-climate-projections.html#cb57-41" aria-hidden="true" tabindex="-1"></a>clim_scen <span class="ot">&lt;-</span> <span class="cn">NULL</span> <span class="co"># We not yet simulate future climate. This follows in the next Subsection below.</span></span>
<span id="cb57-42"><a href="data-on-climate-projections.html#cb57-42" aria-hidden="true" tabindex="-1"></a>station_subset <span class="ot">&lt;-</span> station_data<span class="sc">$</span>STATION_NAMES[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="co"># Selecting 2 example stations, i.e. Alishur_2 and Alishur_3. Normally, one wants to run the function for all stations.</span></span>
<span id="cb57-43"><a href="data-on-climate-projections.html#cb57-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-44"><a href="data-on-climate-projections.html#cb57-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Return VAR model? If we set this parameter to false, the output size of the PT_sim variable will be greatly reduced. </span></span>
<span id="cb57-45"><a href="data-on-climate-projections.html#cb57-45" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>returnVARModel <span class="ot">=</span> <span class="cn">FALSE</span></span>
<span id="cb57-46"><a href="data-on-climate-projections.html#cb57-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Fire up the stochastic VAR machine</span></span>
<span id="cb57-47"><a href="data-on-climate-projections.html#cb57-47" aria-hidden="true" tabindex="-1"></a>PT_sim <span class="ot">&lt;-</span> <span class="fu">wgen_daily_PT</span>(param,station_data,station_subset,clim_scen,param<span class="sc">$</span>returnVARModel)</span></code></pre></div>
<p>The output of <code>RMAWGEN::ComprehensivePrecipitationGenerator()</code> and <code>RMAWGEN::ComprehensivePrecipitationGenerator()</code> are stored in the <code>PT_sim</code> list. Summary statistics of the resulting simulated climate can be obtained by using the <code>riversCentralAsia::wgen_daily_summaryStats()</code> function. For this, the period of interest for comparison (we call this <em>baseline period</em>) needs to be specified by setting <code>param$year_min_Baseline</code> and <code>param$year_max_Baseline</code> as shown below. For each station in the station subset, summary statistics can be shown.</p>
<!--# Housekeeping -->
<!--# SAVING the PT_sim file for later processing -->
<!--# LOADING the PT_sim file for later processing -->
<!--# END HOUSEKEEPING -->
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="data-on-climate-projections.html#cb58-1" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_min_Baseline <span class="ot">&lt;-</span> <span class="dv">2004</span></span>
<span id="cb58-2"><a href="data-on-climate-projections.html#cb58-2" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_max_Baseline <span class="ot">&lt;-</span> <span class="dv">2013</span></span>
<span id="cb58-3"><a href="data-on-climate-projections.html#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="data-on-climate-projections.html#cb58-4" aria-hidden="true" tabindex="-1"></a>clim_scen <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb58-5"><a href="data-on-climate-projections.html#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="data-on-climate-projections.html#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Computing the baseline statistics and comparing it with simulated weather over the same period.</span></span>
<span id="cb58-7"><a href="data-on-climate-projections.html#cb58-7" aria-hidden="true" tabindex="-1"></a>summaryStats <span class="ot">&lt;-</span> <span class="fu">wgen_daily_summaryStats</span>(PT_sim, param, station_data, station_subset,clim_scen)</span>
<span id="cb58-8"><a href="data-on-climate-projections.html#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for the station (i.e. elevation band) Alishur_2 </span></span>
<span id="cb58-9"><a href="data-on-climate-projections.html#cb58-9" aria-hidden="true" tabindex="-1"></a>summaryStats<span class="sc">$</span>Alishur_2</span></code></pre></div>
<pre><code>##         P_baseline_obs P_baseline_sim Tmin_baseline_obs Tmin_baseline_sim
## Min.     -1.153419e-14  -3.448319e-14        -33.087407        -37.959289
## 1st Qu.   1.472035e-02   1.114481e-02        -18.609744        -19.198056
## Median    1.179427e-01   9.179099e-02        -10.156870        -11.134179
## Mean      6.673150e-01   5.551895e-01        -10.885993        -11.210732
## 3rd Qu.   6.200780e-01   5.044390e-01         -2.393775         -2.515402
## Max.      3.974874e+01   1.913596e+01          8.173291          9.480053
##         Tmax_baseline_obs Tmax_baseline_sim
## Min.          -24.4808293       -23.9815519
## 1st Qu.        -7.2860936        -8.0816534
## Median          1.0043645         0.2261556
## Mean            0.3899992         0.1787211
## 3rd Qu.         8.4963461         9.1207188
## Max.           20.4007594        21.7046781</code></pre>
<p>The <code>…_obs</code> identifier refers to the baseline period statistics of the observations (ERA5 data in our case). Converse to this, the <code>…_sim</code> identifier refers to the statistics of generated synthetic climate variable time series using <code>RMAWGEN</code>. The variable <code>clim_scen</code> is set to <code>NULL</code> since we are not (yet) comparing baseline observed climate with future climate scenarios (see Section <a href="data-on-climate-projections.html#FutureDailyClimateSim">3.4.2.4</a> below where this is done).</p>
<p>A graphical comparison of observed monthly versus simulated monthly precipitation values is shown below in Figure <a href="data-on-climate-projections.html#fig:rmawgenMonthlyTotals">3.50</a> for one elevation band, i.e. the Alishur_2 station. The scatter plot comparing monthly total observed versus simulated precipitation totals does not show a systematic bias. Furthermore, the seriality and normality tests are both passed. We thus consider the simulation results of the weather generator adequately represent local climate conditions.</p>
<div class="figure"><span id="fig:rmawgenMonthlyTotalsCoupledModel"></span>
<img src="_bookdown_files/FIG_DATA/RMAWGEN_Models_CoupledModel_monthlyTotalsComparison.jpg" alt="Comparison of monthly observed (ERA5) precipitation values with simulated ones. No systematic bias is visible." width="449" />
<p class="caption">
Figure 3.52: Comparison of monthly observed (ERA5) precipitation values with simulated ones. No systematic bias is visible.
</p>
</div>
</div>
<div id="FutureDailyClimateSim" class="section level4" number="3.4.2.4">
<h4><span class="header-section-number">3.4.2.4</span> Simulating Future Daily Climate</h4>
<p>Using the insights gained so far, we can now generate future <em>daily</em> weather conditioned on the high resolution GCM output as described in the Section <a href="data-on-climate-projections.html#CHELSA21Century">3.4.1</a> above. For the climate impact assessment, we generate a 10-year mid 21st century run from 2051 - 2060 (called Period 1) and an end of 21st century run (2091 - 2100, Period 2) for both, the RCP 4.5 and RCP 8.5 concentration pathways. The climate scenarios will be compared to a baseline climate period from 2004 - 2013. These periods are specified in the following way in the parameters <code>param</code> list.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="data-on-climate-projections.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulation periods</span></span>
<span id="cb60-2"><a href="data-on-climate-projections.html#cb60-2" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_min_Baseline <span class="ot">&lt;-</span> <span class="dv">2004</span></span>
<span id="cb60-3"><a href="data-on-climate-projections.html#cb60-3" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_max_Baseline <span class="ot">&lt;-</span> <span class="dv">2013</span></span>
<span id="cb60-4"><a href="data-on-climate-projections.html#cb60-4" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_min_sim_Period1 <span class="ot">&lt;-</span>  <span class="dv">2051</span></span>
<span id="cb60-5"><a href="data-on-climate-projections.html#cb60-5" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_max_sim_Period1 <span class="ot">&lt;-</span>  <span class="dv">2060</span></span>
<span id="cb60-6"><a href="data-on-climate-projections.html#cb60-6" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_min_sim_Period2 <span class="ot">&lt;-</span>  <span class="dv">2091</span></span>
<span id="cb60-7"><a href="data-on-climate-projections.html#cb60-7" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>year_max_sim_Period2 <span class="ot">&lt;-</span>  <span class="dv">2100</span></span></code></pre></div>
<p>Now we are ready to prepare the climate scenarios<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a>. The function <code>riversCentralAsia::climateScenarioPreparation_RMAWGEN()</code> prepares 2 climate scenarios between the years 2006 - 2100 where the user can define the periods of interest. Here, we want to investigate the 2 scenarios for the mid-21st century and the end of the century as defined above with the <code>param$year_min_sim_Periodx</code> and <code>param$year_min_sim_Periodx</code> parameters.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="data-on-climate-projections.html#cb61-1" aria-hidden="true" tabindex="-1"></a>basin_climScen_Path <span class="ot">&lt;-</span> <span class="st">&#39;./data/AmuDarya/GuntYashikul/ClimateProjections/&#39;</span></span>
<span id="cb61-2"><a href="data-on-climate-projections.html#cb61-2" aria-hidden="true" tabindex="-1"></a>basin_climScen_File <span class="ot">&lt;-</span> <span class="st">&#39;climScen_monthly&#39;</span></span>
<span id="cb61-3"><a href="data-on-climate-projections.html#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="data-on-climate-projections.html#cb61-4" aria-hidden="true" tabindex="-1"></a>clim_scen <span class="ot">&lt;-</span> <span class="fu">climateScenarioPreparation_RMAWGEN</span>(basin_climScen_Path,basin_climScen_File,param)</span></code></pre></div>
<p>We have now defined the 12 precipitation and temperature scenarios, i.e. 2 for each RCP, 3 for each of the climate models available and 2 for each of the periods of interest, 2051 - 2060 and 2091-2100 and can rerun the stochastic weather generator while conditioning the scenarios on the mean future weather states.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="data-on-climate-projections.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute for all stations</span></span>
<span id="cb62-2"><a href="data-on-climate-projections.html#cb62-2" aria-hidden="true" tabindex="-1"></a>station_subset <span class="ot">&lt;-</span> <span class="cn">NULL</span> <span class="co"># We compute climate projections for all subasin elevation bands.</span></span>
<span id="cb62-3"><a href="data-on-climate-projections.html#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="data-on-climate-projections.html#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Return VAR model?</span></span>
<span id="cb62-5"><a href="data-on-climate-projections.html#cb62-5" aria-hidden="true" tabindex="-1"></a>param<span class="sc">$</span>returnVARModel <span class="ot">=</span> <span class="cn">FALSE</span></span>
<span id="cb62-6"><a href="data-on-climate-projections.html#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="data-on-climate-projections.html#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fire up the stochastic weather generator for all climate scenarios</span></span>
<span id="cb62-8"><a href="data-on-climate-projections.html#cb62-8" aria-hidden="true" tabindex="-1"></a>PT_sim_all <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb62-9"><a href="data-on-climate-projections.html#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through all climate scenarios and run models</span></span>
<span id="cb62-10"><a href="data-on-climate-projections.html#cb62-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (idx <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(clim_scen)){</span>
<span id="cb62-11"><a href="data-on-climate-projections.html#cb62-11" aria-hidden="true" tabindex="-1"></a>  PT_sim_all[[idx]] <span class="ot">&lt;-</span> <span class="fu">wgen_daily_PT</span>(param,station_data,station_subset,clim_scen[[idx]],param<span class="sc">$</span>returnVARModel)</span>
<span id="cb62-12"><a href="data-on-climate-projections.html#cb62-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb62-13"><a href="data-on-climate-projections.html#cb62-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-14"><a href="data-on-climate-projections.html#cb62-14" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(PT_sim_all) <span class="ot">&lt;-</span> <span class="fu">names</span>(clim_scen)</span></code></pre></div>
<!--# HOUSEKEEPING -->
<!--# SAVING FILES -->
<!--# LOADING FILES -->
<!--# END HOUSEKEEPING -->
<p>The <code>PT_sim_all</code> list contains the simulated daily minimum and maximum temperatures as well as precipitation values for the future periods of interest. In our case, these are the 10-year periods from 2051-2060 and 2091-2100 for all 3 available GCM models and the two RCPs. Summary statistics can be obtained for all scenarios and all stations with the <code>riversCentralAsia::wgen_daily_summaryStats()</code> function. This allows to carry out different types of top-level quick analyses for getting a good understanding of the future climate in the basin under consideration as a function of the target period and the GCM as well as the RCP. We show a couple of these analyses here.</p>
<p>First, all summary statistics are produced.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="data-on-climate-projections.html#cb63-1" aria-hidden="true" tabindex="-1"></a>PT_sim_stats <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb63-2"><a href="data-on-climate-projections.html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (idx <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(clim_scen)){</span>
<span id="cb63-3"><a href="data-on-climate-projections.html#cb63-3" aria-hidden="true" tabindex="-1"></a>  PT_sim_stats[[idx]] <span class="ot">&lt;-</span> </span>
<span id="cb63-4"><a href="data-on-climate-projections.html#cb63-4" aria-hidden="true" tabindex="-1"></a>    riversCentralAsia<span class="sc">::</span><span class="fu">wgen_daily_summaryStats</span>(PT_sim_all[[idx]],param,station_data,station_subset,clim_scen[[idx]])</span>
<span id="cb63-5"><a href="data-on-climate-projections.html#cb63-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb63-6"><a href="data-on-climate-projections.html#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(PT_sim_stats) <span class="ot">&lt;-</span> <span class="fu">names</span>(clim_scen)</span></code></pre></div>
<p>Before we show how to do some quick analyses, it should be remembered that we use the following definitions: - Baseline Period: 2004 - 2013; future Period 1: 2051 - 2060; and Future Period 2: 2091 - 2100.</p>
<p>For the station/elevation band Alishur_2, we get the following statistics of the daily climate projections under the GCM MIROC5 and RCP 45:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="data-on-climate-projections.html#cb64-1" aria-hidden="true" tabindex="-1"></a>PT_sim_stats<span class="sc">$</span>rcp45_MIROC5_Period1<span class="sc">$</span>Alishur_2</span></code></pre></div>
<pre><code>##         P_baseline_obs P_futurePeriod_sim Tmin_baseline_obs
## Min.     -1.153419e-14      -2.386486e-14        -33.087407
## 1st Qu.   1.472035e-02       1.137278e-02        -18.609744
## Median    1.179427e-01       1.044057e-01        -10.156870
## Mean      6.673150e-01       6.852445e-01        -10.885993
## 3rd Qu.   6.200780e-01       6.077338e-01         -2.393775
## Max.      3.974874e+01       2.368893e+01          8.173291
##         Tmin_futurePeriod_sim Tmax_baseline_obs Tmax_futurePeriod_sim
## Min.               -29.740110       -24.4808293            -20.340536
## 1st Qu.            -15.362856        -7.2860936             -5.538543
## Median              -7.659832         1.0043645              2.844080
## Mean                -7.155001         0.3899992              3.561524
## 3rd Qu.              1.658264         8.4963461             13.508027
## Max.                14.897473        20.4007594             24.323957</code></pre>
<p>When comparing precipitation for the baseline period and the 2051 - 2060 period, the MIROC5 model suggests a slight increase of precipitation values in the Eastern Pamirs relative to the baseline (please note that the precipitation values in the table are in mm/day). At the same time, minimum mean temperatures are increasing from -10.89 degrees Celsius to -7.15 degrees Celsius, i.e. and increase of a remarkable 3.74 degrees. Our gut feeling tells us that this increase will be even more pronounced at the end of the 21st century and under RCP85. Let’s check!</p>
<p>First, we display the summary statistics for Alishur_2 of the GCM MIROC5 and the RCP45 for Period 2. As is visible in the table below, no significant changes are expected in terms of mean precipitation, also in Period 2 under this climate scenario and for this model. However, a further warming is expected where minimum mean temperatures increase to -6.38 degrees Celsius and and the mean maximum temperatures increase from 3.56 to 4.39 degrees Celsius. This suggests a pronounced winter warming.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="data-on-climate-projections.html#cb66-1" aria-hidden="true" tabindex="-1"></a>PT_sim_stats<span class="sc">$</span>rcp45_MIROC5_Period2<span class="sc">$</span>Alishur_2</span></code></pre></div>
<pre><code>##         P_baseline_obs P_futurePeriod_sim Tmin_baseline_obs
## Min.     -1.153419e-14      -3.214945e-14        -33.087407
## 1st Qu.   1.472035e-02       1.176385e-02        -18.609744
## Median    1.179427e-01       9.878187e-02        -10.156870
## Mean      6.673150e-01       6.881313e-01        -10.885993
## 3rd Qu.   6.200780e-01       5.786604e-01         -2.393775
## Max.      3.974874e+01       2.598245e+01          8.173291
##         Tmin_futurePeriod_sim Tmax_baseline_obs Tmax_futurePeriod_sim
## Min.               -31.997585       -24.4808293            -19.351808
## 1st Qu.            -14.480643        -7.2860936             -4.926043
## Median              -6.615511         1.0043645              3.641779
## Mean                -6.379430         0.3899992              4.391877
## 3rd Qu.              1.938303         8.4963461             14.078694
## Max.                15.692796        20.4007594             27.346588</code></pre>
<p>Finally, we do the same for this station/elevation band using the GCM MIROC5 and the RCP85 for Period 2.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="data-on-climate-projections.html#cb68-1" aria-hidden="true" tabindex="-1"></a>PT_sim_stats<span class="sc">$</span>rcp85_MIROC5_Period2<span class="sc">$</span>Alishur_2</span></code></pre></div>
<pre><code>##         P_baseline_obs P_futurePeriod_sim Tmin_baseline_obs
## Min.     -1.153419e-14      -4.613131e-14        -33.087407
## 1st Qu.   1.472035e-02       1.446667e-02        -18.609744
## Median    1.179427e-01       1.274579e-01        -10.156870
## Mean      6.673150e-01       8.162968e-01        -10.885993
## 3rd Qu.   6.200780e-01       6.999277e-01         -2.393775
## Max.      3.974874e+01       2.861400e+01          8.173291
##         Tmin_futurePeriod_sim Tmax_baseline_obs Tmax_futurePeriod_sim
## Min.               -27.939768       -24.4808293            -16.552664
## 1st Qu.            -11.924017        -7.2860936             -2.694583
## Median              -4.036578         1.0043645              6.522826
## Mean                -3.175482         0.3899992              7.111490
## 3rd Qu.              6.167460         8.4963461             17.411537
## Max.                19.289063        20.4007594             29.213902</code></pre>
<p>It can easily be seen that our intuition from above is correct and that the modeling results for example suggest a 7.71 degrees warming of the minimum mean temperatures over this period. At the same time, the model suggests that mean precipitation is slightly increasing from approx. 245 mm/year to 298 mm/year. This corresponds to an increase of approx. 22 % relative to the baseline.</p>
<p>With a projected mean precipitation of 332 mm/year (increase of approx. 36 % relative to baseline), the GCM ACCESS1_3 projects the most pronounced increase in precipitation for Alishur_2 under the RCP85 for the period 2091-2100. The GCM CMCC_CM even suggests a slight decrease of total annual precipitation relative to the baseline. While precipitation projections of GCMs are notoriously uncertain, one relatively robust conclusion to make is that precipitation levels are expected to stay at the current levels or slightly increase. All these findings now require us to study with great care implications on the hydrology of the river basins in the region.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="data-on-climate-projections.html#cb70-1" aria-hidden="true" tabindex="-1"></a>PT_sim_stats<span class="sc">$</span>rcp85_ACCESS1_3_Period2<span class="sc">$</span>Alishur_2</span></code></pre></div>
<pre><code>##         P_baseline_obs P_futurePeriod_sim Tmin_baseline_obs
## Min.     -1.153419e-14      -6.337539e-14        -33.087407
## 1st Qu.   1.472035e-02       1.072765e-02        -18.609744
## Median    1.179427e-01       9.955763e-02        -10.156870
## Mean      6.673150e-01       9.109544e-01        -10.885993
## 3rd Qu.   6.200780e-01       6.344134e-01         -2.393775
## Max.      3.974874e+01       5.413337e+01          8.173291
##         Tmin_futurePeriod_sim Tmax_baseline_obs Tmax_futurePeriod_sim
## Min.               -28.262056       -24.4808293            -15.105202
## 1st Qu.            -12.339332        -7.2860936             -1.919159
## Median              -5.582341         1.0043645              5.690707
## Mean                -4.861328         0.3899992              6.521103
## 3rd Qu.              3.320528         8.4963461             15.812779
## Max.                14.406063        20.4007594             26.480914</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="data-on-climate-projections.html#cb72-1" aria-hidden="true" tabindex="-1"></a>PT_sim_stats<span class="sc">$</span>rcp85_CMCC_CM_Period2<span class="sc">$</span>Alishur_2</span></code></pre></div>
<pre><code>##         P_baseline_obs P_futurePeriod_sim Tmin_baseline_obs
## Min.     -1.153419e-14      -4.463575e-14        -33.087407
## 1st Qu.   1.472035e-02       9.058688e-03        -18.609744
## Median    1.179427e-01       7.933737e-02        -10.156870
## Mean      6.673150e-01       6.559270e-01        -10.885993
## 3rd Qu.   6.200780e-01       4.975115e-01         -2.393775
## Max.      3.974874e+01       2.489362e+01          8.173291
##         Tmin_futurePeriod_sim Tmax_baseline_obs Tmax_futurePeriod_sim
## Min.               -28.453681       -24.4808293            -16.855502
## 1st Qu.             -9.314596        -7.2860936             -1.298192
## Median              -1.021698         1.0043645              6.787816
## Mean                -1.957580         0.3899992              7.465019
## 3rd Qu.              5.594001         8.4963461             16.946780
## Max.                16.520962        20.4007594             28.491711</code></pre>
<p>For this purpose, we convert these daily climatologies into hourly ones and export them as scenario files that can be read into RS MINERVE where we can perform hydrological scenario analysis. The downscaling to hourly values as well as the exporting is shown in the Section below.</p>
</div>
<div id="exporting-climate-scenarios-as-.csv-files-for-import-in-rs-minerve" class="section level4" number="3.4.2.5">
<h4><span class="header-section-number">3.4.2.5</span> Exporting Climate Scenarios as .csv-files for import in RS MINERVE</h4>
<p>For exporting to RS MINERVE, a .csv file needs to be generated very much alike the one described in Section <a href="Data-ClimateReanalysisData.html#era5DownscalingDataExportRSMINERVE">3.3.2.4</a>. Prior to exporting such scenario-dependent files, we need to generate hourly time series from the daily simulated ones. To do this, different approaches are chosen for the precipitation values as well as the temperature time series. The conversion can automatically be done with the helper function <code>riversCentralAsia::generateHourlyFromDaily_PT()</code> that accepts the daily climate scenarios as variable from which it downscales to hourly data and prepares the tabular export as .csv-file for later import in RS MINVERVE.</p>
<p>As for total daily precipitation [mm/day], it is available for each day for the future periods of interest and for each station/elevation band. <code>riversCentralAsia::generateHourlyFromDaily_PT()</code> converts these values by uniformly distribution the total daily precipitation over the 24 hours within one day, i.e. from <code>00:00:00</code> to <code>23:00:00</code>. More details on this can be found in the help section of the function.</p>
<p>For temperature, the challenge is a bit bigger since we ideally would want to take into account the diurnal cycle of temperature to vary between the daily minimum and maximum temperatures characteristically. How to get the diurnal cycle for the stations/elevation bands?</p>
<p>What is being proposed here is to use the hourly ERA5 data over the baseline period and to extract a mean dirurnal cycle for each station there measured over all baseline period observation days. Under the assumption that these station cycles remain the same in the future, they are adjusted for each day so that minimum and maximum daily temperatures from the climate scenarios correspond to minimum and maximum diurnal cycle values. As is shown below, the function <code>riversCentralAsia::computeDiurnalTemperatureCycle()</code> computes these diurnal station cycles.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="data-on-climate-projections.html#cb74-1" aria-hidden="true" tabindex="-1"></a>filePath <span class="ot">&lt;-</span> <span class="st">&#39;./data/AmuDarya/GuntYashikul/RSMinerve/&#39;</span></span>
<span id="cb74-2"><a href="data-on-climate-projections.html#cb74-2" aria-hidden="true" tabindex="-1"></a>fileName <span class="ot">&lt;-</span> <span class="st">&#39;Gunt_Yashikul_1981_2013_db.csv&#39;</span></span>
<span id="cb74-3"><a href="data-on-climate-projections.html#cb74-3" aria-hidden="true" tabindex="-1"></a>era5_gunt_yashikul <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="fu">paste0</span>(filePath,fileName),<span class="at">sep=</span><span class="st">&#39;,&#39;</span>) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb74-4"><a href="data-on-climate-projections.html#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="data-on-climate-projections.html#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Subcatchment suspects to delete because we do not use them in the RR Model</span></span>
<span id="cb74-6"><a href="data-on-climate-projections.html#cb74-6" aria-hidden="true" tabindex="-1"></a>idx2del <span class="ot">&lt;-</span> (era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_1&#39;</span>)<span class="sc">|</span>(era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_2&#39;</span>)<span class="sc">|</span></span>
<span id="cb74-7"><a href="data-on-climate-projections.html#cb74-7" aria-hidden="true" tabindex="-1"></a>  (era5_gunt_yashikul[<span class="dv">1</span>,]<span class="sc">==</span><span class="st">&#39;Gunt_DS_3&#39;</span>)</span>
<span id="cb74-8"><a href="data-on-climate-projections.html#cb74-8" aria-hidden="true" tabindex="-1"></a>era5_gunt_yashikul <span class="ot">&lt;-</span> era5_gunt_yashikul <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">which</span>(<span class="sc">!</span>idx2del))</span>
<span id="cb74-9"><a href="data-on-climate-projections.html#cb74-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-10"><a href="data-on-climate-projections.html#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute diurnal cycle</span></span>
<span id="cb74-11"><a href="data-on-climate-projections.html#cb74-11" aria-hidden="true" tabindex="-1"></a>diurnalCycle <span class="ot">&lt;-</span> <span class="fu">computeDiurnalTemperatureCycle</span>(era5_gunt_yashikul,param)</span>
<span id="cb74-12"><a href="data-on-climate-projections.html#cb74-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-13"><a href="data-on-climate-projections.html#cb74-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple visualization</span></span>
<span id="cb74-14"><a href="data-on-climate-projections.html#cb74-14" aria-hidden="true" tabindex="-1"></a>diurnalCycle <span class="sc">%&gt;%</span> <span class="fu">pivot_longer</span>(<span class="sc">-</span>hour) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span> </span>
<span id="cb74-15"><a href="data-on-climate-projections.html#cb74-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(.,<span class="fu">aes</span>(<span class="at">x=</span>hour,<span class="at">y=</span>value,<span class="at">colour=</span>name)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;ERA5 Diurnal T Variation, Gunt-Yashikul River Subbasins&quot;</span>)</span></code></pre></div>
<p><img src="applied-hydrological-modeling-central-asia_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>Using <code>riversCentralAsia::generateHourlyFromDaily_PT()</code>, the daily climate scenario files can be produced in a very simple manner.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="data-on-climate-projections.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Producing the hourly climate scenarios</span></span>
<span id="cb75-2"><a href="data-on-climate-projections.html#cb75-2" aria-hidden="true" tabindex="-1"></a>climScen_hourly <span class="ot">&lt;-</span> <span class="fu">generateHourlyFromDaily_PT</span>(PT_sim_all,era5_gunt_yashikul,param)</span>
<span id="cb75-3"><a href="data-on-climate-projections.html#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding the required header information to the data frames for each climate scenario</span></span>
<span id="cb75-4"><a href="data-on-climate-projections.html#cb75-4" aria-hidden="true" tabindex="-1"></a>headerRows<span class="ot">&lt;-</span> era5_gunt_yashikul[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,] <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">which</span>(era5_gunt_yashikul[<span class="dv">5</span>,]<span class="sc">==</span><span class="st">&#39;Q&#39;</span>))</span>
<span id="cb75-5"><a href="data-on-climate-projections.html#cb75-5" aria-hidden="true" tabindex="-1"></a>climScen_hourly_rsminerve <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb75-6"><a href="data-on-climate-projections.html#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (idx <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(climScen_hourly)){</span>
<span id="cb75-7"><a href="data-on-climate-projections.html#cb75-7" aria-hidden="true" tabindex="-1"></a>  climScen2Export <span class="ot">&lt;-</span> climScen_hourly[[idx]] <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), as.character))</span>
<span id="cb75-8"><a href="data-on-climate-projections.html#cb75-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(climScen2Export) <span class="ot">&lt;-</span> <span class="fu">names</span>(headerRows)</span>
<span id="cb75-9"><a href="data-on-climate-projections.html#cb75-9" aria-hidden="true" tabindex="-1"></a>  climScen_hourly_rsminerve[[idx]] <span class="ot">&lt;-</span> headerRows <span class="sc">%&gt;%</span> <span class="fu">add_row</span>(climScen2Export)</span>
<span id="cb75-10"><a href="data-on-climate-projections.html#cb75-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb75-11"><a href="data-on-climate-projections.html#cb75-11" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(climScen_hourly_rsminerve) <span class="ot">&lt;-</span> <span class="fu">names</span>(clim_scen)</span></code></pre></div>
<p>Now, finally, we can store these files as climate scenario files on the disk for later importing into RS MINERVE.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="data-on-climate-projections.html#cb76-1" aria-hidden="true" tabindex="-1"></a>outputPath <span class="ot">&lt;-</span> <span class="st">&#39;./data/AmuDarya/GuntYashikul/RSMinerve/&#39;</span> <span class="co"># Specify the output path of the files</span></span>
<span id="cb76-2"><a href="data-on-climate-projections.html#cb76-2" aria-hidden="true" tabindex="-1"></a>names2Save <span class="ot">&lt;-</span> <span class="fu">names</span>(climScen_hourly_rsminerve) <span class="co"># Specification of the file names (do not change)</span></span>
<span id="cb76-3"><a href="data-on-climate-projections.html#cb76-3" aria-hidden="true" tabindex="-1"></a>names2Save_prefix <span class="ot">&lt;-</span> <span class="st">&#39;Gunt_Yashikul_&#39;</span> <span class="co"># Change according to the basin that you are working with</span></span>
<span id="cb76-4"><a href="data-on-climate-projections.html#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (idx <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(climScen_hourly_rsminerve)){</span>
<span id="cb76-5"><a href="data-on-climate-projections.html#cb76-5" aria-hidden="true" tabindex="-1"></a>  fileName <span class="ot">&lt;-</span> <span class="fu">paste0</span>(names2Save_prefix,names2Save[idx],<span class="st">&#39;.csv&#39;</span>)</span>
<span id="cb76-6"><a href="data-on-climate-projections.html#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write.table</span>(climScen_hourly_rsminerve[[idx]],</span>
<span id="cb76-7"><a href="data-on-climate-projections.html#cb76-7" aria-hidden="true" tabindex="-1"></a>              <span class="fu">paste0</span>(outputPath,fileName),<span class="at">sep=</span><span class="st">&#39;,&#39;</span>,</span>
<span id="cb76-8"><a href="data-on-climate-projections.html#cb76-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">row.names =</span> <span class="cn">FALSE</span>,<span class="at">col.names=</span><span class="cn">FALSE</span>,</span>
<span id="cb76-9"><a href="data-on-climate-projections.html#cb76-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">quote=</span><span class="cn">FALSE</span>,<span class="at">append=</span><span class="cn">FALSE</span>)</span>
<span id="cb76-10"><a href="data-on-climate-projections.html#cb76-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="7">
<li id="fn7"><p>This is the same algorithm that was used to produce high-resolution reanalysis data as discussed in Chapter @ref(<a href="Data::ClimateReanalysisData" class="uri">Data::ClimateReanalysisData</a>).<a href="data-on-climate-projections.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>If you download these data, it is advisable to maintain the directory structure as given via the Dropbox link. Please note that the entire directory is 4.79 GB of data.<a href="data-on-climate-projections.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p>Detailed information about the core functions of RMAWGEN can be obtained by consulting their help, i.e. by for example typing <code>?ComprehensivePrecipitationGenerator</code>.<a href="data-on-climate-projections.html#fnref9" class="footnote-back">↩︎</a></p></li>
<li id="fn10"><p>The prepared monthly climate scenarios of this RS MINVERVE model can be found in this directory <code>'./data/AmuDarya/GuntYashikul/ClimateProjections/'</code>. Since RMAWGEN requires precipitation, mean minimum and mean maximum temperature on a monthly basis, these data are prepared using the function <code>riversCentralAsia::climateScenarioPreparation_RMAWGEN()</code> for the periods of interest in the future.<a href="data-on-climate-projections.html#fnref10" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="Data-ClimateReanalysisData.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="snow-cover-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07_DATA.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["applied-hydrological-modeling-central-asia.pdf", "applied-hydrological-modeling-central-asia.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
